### ISSUE TITLE
Sponge incompatibility

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#1]
When you start the mod on a sponge server the mod loads a class before sponge so you get quick crashes. 
Here is the [log](https://pastebin.com/HF3TAD3K)

Everything works fine with that modpack in singleplayer

**Comment by jbredwards** [comment]
issue addressed on curse page

**Comment by Druwan-ctrl** [comment]
This issue is not related to that one and is still present in 1.1

**Comment by jbredwards** [comment]
just released a new version which may fix your issue. I'm not too familiar with SpongeForge, so can let me know if it works if you can! :)

**Comment by Druwan-ctrl** [comment]
I will keep you updated! For now it seems the error is still there, if you can find the source of the problem it would be awesome! This mod is amazing, sharing the experience on a server would be incredible!

**Comment by jbredwards** [comment]
I think I actually fixed it this time lol

**Comment by Druwan-ctrl** [comment]
You did it!
