### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#10]
I have a rendering issue with fluidlogged v1.4, as you can see flowing water does not render correctly

![2021-06-20_11 46 02](https://user-images.githubusercontent.com/69646703/122670463-8038d180-d1c2-11eb-9048-8b903c0a0345.png)

**Comment by jbredwards** [comment]
This will be fixed next release, which will be out once I can fix this other bug linked [here](https://imgbb.com/6H34Wrn).

**Comment by jbredwards** [comment]
fixed in v1.4.1!
