### ISSUE TITLE
World Generate Bug With GalactiCraft

### ISSUE THREAD

**Issue by 0XPYEX0** [jbredwards/Fluidlogged-API#101]
**Describe the bug**
There is a bug about world generate with GalactiCraft

**To Reproduce**
1. Go to "asteroid belt" (A world that generated by GalactiCraft, it's a planet)
2. See error

**Expected behavior**
Enter the world normally

**Screenshots**
No screenshots for this.

**Logs**
[Click Here](https://paste.ubuntu.com/p/7Z9NvFPY3k/).

**Additional context**
No

**Comment by jbredwards** [comment]
I can't recreate this with the latest commit + [galacticraft legacy](https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy), so either this issue was fixed at some point accidentally (lol), or galacticraft legacy changed how galacticraft does its chunk gen and that fixed it

**Comment by jbredwards** [comment]
fixed in v1.8.1
