### ISSUE TITLE
Streams mod texture bug

### ISSUE THREAD

**Issue by BIoxyest** [jbredwards/Fluidlogged-API#102]
The Streams river texture goes missing when Fluidlogged is installed with it

1. Install Fluidlogged-API and Streams https://www.curseforge.com/minecraft/mc-mods/streams
2. Find a stream
![2022-05-23_01 26 56](https://user-images.githubusercontent.com/51765001/169760997-f2160e8b-f11b-4fe8-88c6-08dfb517aa6e.png)

[latest.log](https://github.com/CleanroomMC/Fluidlogged-API/files/8752142/latest.log)
[debug.log](https://github.com/CleanroomMC/Fluidlogged-API/files/8752143/debug.log)

**Comment by embeddedt** [comment]
This is already fixed (#89) but hasn't been released yet.
