### ISSUE TITLE
Some water untextured (w/ other mods)

### ISSUE THREAD

**Issue by SlasherGuy** [jbredwards/Fluidlogged-API#103]
**Describe the bug**
Randomly water is generated untextured. It seems to be contained in that specific biome, but sometimes the same biome is normal.

**To Reproduce**
1. Generate a new world 
2. Fly around a bit (sometimes I find it right away, others it can take a few mins)
3. Water occasionally not blue :( seemingly no rhyme or reason to this.

**Expected behavior**
Water to be generated with a texture

**Screenshots**
![unknown](https://user-images.githubusercontent.com/37916121/170905813-b2bead44-d5a5-4466-8618-8c6b35620998.png)

**Logs**
[latest.log](https://github.com/CleanroomMC/Fluidlogged-API/files/8797153/latest.log)
(have fun, that's massive)

**Additional context**
Playing on a custom modified MC Eternal modpack, water never had any issues before adding this mod. We made a few new worlds just in case, it kept happening.

**Comment by SlasherGuy** [comment]
May not be BoP, seems 100% random now

**Comment by jbredwards** [comment]
Judging by the mini map it's possible the untextured water is from the streams mod, which has already been fixed for the next update, try [this](https://cdn.discordapp.com/attachments/785959414632939571/980859413067886652/Fluidlogged-API-v1.8.0b-mc1.12.2.jar) & let me know if it fixes your issue

**Comment by SlasherGuy** [comment]
Worked like a charm. Dunno how I missed streams going through the list, should've been obvious. Either way thank you so much!
