### ISSUE TITLE
[SUGGESTION] Print all unknown registry names

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#104]
**Is your feature request related to a problem? Please describe.**
I have a pretty heavy modpack, so it takes a hot min to launch. Issue with that is if Fluidlogged API doesn't find a registry name it crashes, but it only prints out the first unknown name. I usually add a lot of blocks simultaneously, and if there are multiple misspelled entries in the configs I have to relaunch the game multiple times to find them all.

**Describe the solution you'd like**
When it crashes it should continue looking through the list and print out *all* unknown registry names, not just the first one it can't find.

**Comment by embeddedt** [comment]
Even more ideal would be if Fluidlogged could reload the config at runtime, and thus save you from having to relaunch the pack to make a block be fluidloggable.

**Comment by xemnes** [comment]
id like this too, also any way to mitigate the crashing? if it finds an unknown block in the array, ignore it and print a message in console saying which block definitions are invalid perhaps. it is a little annoying to have to wait 5 mins for almost the entirety of a large modpack to load only for it to crash near the end due to a block id being misspelt lol.

it also makes testing individual mods with fluidlogged a bit of a pain too since disabling mods with ids in the list will also cause a crash

**Comment by jbredwards** [comment]
> Even more ideal would be if Fluidlogged could reload the config at runtime, and thus save you from having to relaunch the pack to make a block be fluidloggable.

True, unfortunately I'm not good enough with guis to add this :(

> any way to mitigate the crashing? if it finds an unknown block in the array, ignore it and print a message in console saying which block definitions are invalid perhaps

Yeah I can do this, it'll be a part of the next update for sure!

**Comment by embeddedt** [comment]
> True, unfortunately I'm not good enough with guis to add this :(

A GUI isn't necessary. Just a simple `/fl_reload` server-side command that ops can run would suffice.

**Comment by xemnes** [comment]
yeah a command is more than enough tbh

**Comment by Titoo8899** [comment]
I find the idear of embeddedt with "/fl_reload" very good a simple name for a command and it is easy to build this and I find it will work then you have this build

**Comment by jbredwards** [comment]
added in v1.8.1d, forgot that I never closed this 😅
