### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#105]
**Describe the bug**
A ticking entity crash appeared while flying and generating new chunks in creative mode.

**To Reproduce**
1. Install following mods:
   - MixinBooter | 4.2
   - Aqua Acrobatics | 1.14.1
   - Biomes O' Plenty | 7.0.1.2445
   - Fluidlogged-API | 1.8.0
   - Forgelin | 1.8.4
   - [Greenery](https://www.curseforge.com/minecraft/mc-mods/greenery)
   - [SimpleDifficulty for Underdog](https://www.curseforge.com/minecraft/mc-mods/simpledifficulty-for-underdog)

2. Fastly fly around in creative mode.
3. Crash?

**Logs**
[Latest Log](https://gist.github.com/juraj-hrivnak/da93a4fe94b3ea3d8c06ecbfbb611c5a)
[Crash Report](https://gist.github.com/juraj-hrivnak/6a74956ecf6eadce1ae40b126af2be61)

**Comment by embeddedt** [comment]
@jbredwards Some quick research suggests that fastutil maps are likely to throw `ArrayIndexOutOfBoundsException` if accessed from multiple threads, not sure how this could happen though?

**Comment by Rongmario** [comment]
Perhaps the Chunk Batcher threads are manipulating the same map at the same time, maybe defensive copies of the maps should be made when a `ChunkCache` is created?

**Comment by embeddedt** [comment]
@juraj-hrivnak Can you try this version, and see if it fixes your issue? I've done some refactoring that should address the problem in theory.

https://cdn.discordapp.com/attachments/847262784530022412/987859743324377098/Fluidlogged-API-v1.8.0b-mc1.12.2.jar

**Comment by juraj-hrivnak** [comment]
Yes, that did work🎉
While using the same seed, the new world didn't crash using v1.8.0b
