### ISSUE TITLE
Fluids are rendering sides where they should not

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#106]
**Describe the bug**
When Fluidlogged API v1.8.0 is installed, sides are rendering where they should not.
![2022-06-18_18 32 04](https://user-images.githubusercontent.com/71150936/174448111-60329dcd-19fc-4844-9cda-64900d4cffa0.png)

**Expected behaviour**
Vanilla Minecraft, no sides behind blocks are rendered.
![2022-06-18_18 38 49](https://user-images.githubusercontent.com/71150936/174448255-8646aa3d-86f9-48a4-99eb-7ef03ab44529.png)

**Comment by jbredwards** [comment]
fixed in v1.8.1
