### ISSUE TITLE
Incompatibility with underwater plants from Backported Flora mod

### ISSUE THREAD

**Issue by wed15** [jbredwards/Fluidlogged-API#107]
**Describe the bug**
With Fluidloggedapi v1.8.0 installed, seagrass and kelp block from [Backported Flora](https://www.curseforge.com/minecraft/mc-mods/backported-flora) don't rendered correctly, similar to #98. In v1.7.2b they look fine.

**Screenshots**
![2022-06-19_17 42 39](https://user-images.githubusercontent.com/86100898/174474079-61b73cfd-eefc-468b-9342-0a6efd984e2e.png)
![2022-06-19_17 42 46](https://user-images.githubusercontent.com/86100898/174474082-7f0bb79e-82e6-4cac-93d4-17629bbaa113.png)

**Logs**
[log](https://gist.github.com/wed15/a8e12254da1935b7f5c4cd9ae1f28e61)
[debug](https://gist.github.com/wed15/ab976b6839eeeb76ed7828c084ed6151)

**Additional context**
This visual bug also happens with [Greenery](https://www.curseforge.com/minecraft/mc-mods/greenery) mod(forked version of Backported Flora, formerly known as Underdog Flora).

**Comment by jbredwards** [comment]
fixed in v1.8.1
