### ISSUE TITLE
Please allow rails to be fluidlogged. Also, fix the wiki.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Fluidlogged-API#109]
**Is your feature request related to a problem? Please describe.**
No wiki exists for adding blocks to the config.

**Describe the solution you'd like**
Please finish the wiki, so I know what this 'format' is. If its some weird org.blabla.net.this.minecraft:torch, then at least allow modid:block.
![image](https://user-images.githubusercontent.com/51277766/175451310-fea0c9e4-b9d9-4212-a850-a3886da04f95.png)

**Comment by jbredwards** [comment]
the developer wiki is bring worked on, but I did add finish the config section... also rails are fluidloggable by default
edit: link [https://github.com/CleanroomMC/Fluidlogged-API/wiki/Config](https://github.com/CleanroomMC/Fluidlogged-API/wiki/Config)
