### ISSUE TITLE
Fluid disappears when activating trapdoor (by Redstone) in fluid 

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#11]
- This is a simple contraption I made:
![2021-06-24_18 25 05](https://user-images.githubusercontent.com/71150936/123299208-91af1000-d519-11eb-9efb-a6f0937c8f70.png)
It's trapdoors powered by Redstone.
![2021-06-24_18 24 53](https://user-images.githubusercontent.com/71150936/123299362-bc00cd80-d519-11eb-974b-f40191296dca.png)

And basically, **when you activate it, the water disappears.**
![2021-06-24_18 25 18](https://user-images.githubusercontent.com/71150936/123299463-d9359c00-d519-11eb-9962-28ac2415a583.png)

- I can also prove that this happens not only to vanilla water but all moded fluids.
- It does not happen when a player right-clicks it.

**Comment by jbredwards** [comment]
fixed in v1.4.2!

**Comment by juraj-hrivnak** [comment]
Thank you for a quick fix!
I'm really enjoying playing with this mod!
