### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#111]
**Describe the bug**
After updating to 1.8.1b from 1.8.0b, the game crashes when you toss items into any liquid.
The Greenery mod is necessary here, so it could probably be its fault. 

**To Reproduce**
1. Install the following mods:
   - Fluidlogged-API - 1.8.1b
   - [Greenery](https://www.curseforge.com/minecraft/mc-mods/greenery) - 1.4
   - Shadowfacts' Forgelin (Dependency)
2. Throw some items into the water.
3. Crash.

**Logs**
[Latest Log](https://gist.github.com/juraj-hrivnak/40d7eec79b8f90fe2af7ad9277258826)
[Crash Report](https://gist.github.com/juraj-hrivnak/e5d8656e1a2a8acc666459d8029d5571)

**Comment by jbredwards** [comment]
from my testing this crash happens when an entity collides with a fluid block that doesn't use `IExtendedBlockState` ( `BlockLiquid` & `BlockFluidBase` use it for example). I'll add a check for "pseudo waterlogged blocks" (ie. the blocks from Greenery & Coralreef) next version

**Comment by jbredwards** [comment]
fixed in v1.8.1c
