### ISSUE TITLE
Error filling water bottles.

### ISSUE THREAD

**Issue by MasterPM724LTJT103** [jbredwards/Fluidlogged-API#113]
When installing the mod on the assembly, the opportunity to create an item <minecraft:potion> is lost.with Tag({Potion: "minecraft:water"}), the <minecraft:potion> item is created instead.
With the established fashion , reality:
![2022-07-08_00 55 34](https://user-images.githubusercontent.com/86922810/177879390-fbfa8f54-d116-46a4-ae7b-3afe88e65f5c.png)
![2022-07-08_00 55 37](https://user-images.githubusercontent.com/86922810/177879393-19d8989c-25e3-41de-9c21-0f295938e894.png)
Expectation:
![2022-07-08_01 01 00](https://user-images.githubusercontent.com/86922810/177879394-42673cc7-d684-40b0-96cd-97ff1b064fb3.png)
![2022-07-08_01 01 01](https://user-images.githubusercontent.com/86922810/177879397-c0db2919-1f8e-4e71-b7a2-902ea20b91c5.png)

**Comment by jbredwards** [comment]
all fluidlogged api does is change the criteria for creating a water bottle (it does this so waterlogged blocks work), doesn't change resulting item, perhaps some sort of conflict? Send your mod list

**Comment by MasterPM724LTJT103** [comment]
buildcraftlib@7.99.24.8,supermartijn642configlib@1.0.9a,netherportalfix@5.3.17,creativecoredummy@1.0.0,buildcraftenergy@7.99.24.8,aether@0.3.0,futuremc@0.2.6,netherbackport@1.0.0,mtrm@1.2.2.30,betternether@0.1.8.6,mcwwindows@1.0,jeibees@0.9.0.5,ctm@MC1.12.2-1.0.2.31,advsolarpatch@1.2.1,forgelin@1.8.4,bookshelf@2.3.590,microblockcbe@2.6.2.83,randompatches@1.12.2-1.22.1.10,llibrary@1.7.19,projectred-illumination@4.9.4.120,cofhworld@1.4.0,ic2magma@1.0 - MC 1.12.2,mcwdoors@1.3,additionalstructures@2.5.0,waila@1.8.26,agriseasons@1.0.2,dynview@1.3,fpsreducer@mc1.12.2-1.20,jeresources@0.9.2.60,openmodularturrets@3.2.0-379,twilightforest@3.11.1021,advmachinespatch@1.0,corpse@1.12.2-1.0.8,betterpingdisplay@1.0,advanced_machines@61.0.1,unidict@1.12.2-3.0.10,littleframes@1.0.0,crafttweakerjei@2.0.3,betterspawnercontrol@1.5,mcwtrpdoors@1.0.2,supermartijn642corelib@1.0.16b,littletilescore@1.0.0,projectred-core@4.9.4.120,ic2@2.8.221-ex112,patchouli@1.0-23.6,buildcraftbuilders@7.99.24.8,collective@3.0,buildcraftfactory@7.99.24.8,advanced_solar_panels@4.3.0,projectred-fabrication@4.9.4.120,projectred-transmission@4.9.4.120,projectred-exploration@4.9.4.120,FML@8.0.99.99,obfuscate@0.4.2,customnpcs@1.12,projectred-integration@4.9.4.120,advmachinespatchcore@1.0,buildcraftcompat@7.99.24.8,forgemultipartcbe@2.6.2.83,lanserverproperties@1.0,configurablebeaconscore@@VERSION@,jetif@1.5.2,energycontrol@1.12.2-0.1.15,codechickenlib@3.2.3.358,fastleafdecay@v14,netherex@2.2.5,buildcraftcore@7.99.24.8,agricraft@2.12.0-1.12.2-b2,serenetweaks@0.0.1,ctgui@1.0.0,doubledoors@2.5,torchslabmod@v1.5.2,cgm@0.15.3,jei@4.16.1.302,buildcrafttransport@7.99.24.8,giacomos_bookshelf@1.2,chunkpregenerator@2.5.0,masonry_blocks@1.0,wawla@2.6.275,betterportals@0.3.7.7,mcp@9.42,journeymap@1.12.2-5.7.1,naturescompass@1.8.5,sereneseasons@1.2.18,chameleon@1.12-4.1.3,configurablebeacons@1.0.0,inventorytweaks@1.63+release.109.220f184,omlib@3.2.0-256,breedablekillerrabbit@1.6,orbis-lib@0.2.0,iceandfire@1.9.1,walljump@1.3.2,tlauncher_custom_cape_skin@1.4,crafttweaker@4.1.20,projectred-compat@1.0,realserene@1.4.3,ido@2.0.0-B,forge@14.23.5.2860,jabcm@0.0.6_A,ruins@17.2,phosphor-lighting@1.12.2-0.2.6,buildcraftrobotics@7.99.24.8,orelib@3.6.0.1,dsurround@@VERSION@,ironchest@1.12.2-7.0.67.844,variedcommodities@1.12.2,minecraft@1.12.2,creativecore@1.10.0,movingelevators@1.3.6,extrautils2@1.0,jeiintegration@1.6.0,quark@r1.6-179,cookiecore@2.0.0,fluidlogged_api@1.8.0,jeivillagers@1.0,securitycraft@v1.8.23.2,autoreglib@1.3-32,keywizard@1.12.2-1.7.3,libraryex@1.2.2,sit@v1.3,performant@1.12.2-1.5,doubleslabs@0.12.2,mrtjpcore@2.1.4.43,offlineskins@1.12.2-v6,railcraft@12.0.0,wanionlib@1.12.2-2.5,appleskin@1.0.14,infinitylib@1.12.2-1.12.1,connectedglass@1.1.3,minecraftmultipartcbe@2.6.2.83,friendlyfire@1.5.12,littletiles@1.5.0,forestry@5.8.2.422

**Comment by jbredwards** [comment]
sorry for the delay, I still can't recreate this but it should be fixed in v1.9.0.5

**Comment by SlayerTheChikken** [comment]
This is still an issue in v1.9.0.6 for my modpack Tekxit 3.14 version 1.0.91, not sure what mod is conflicting with it though.

Common mods between the two bug reports: littletiles, appleskin, wanionlib, railcraft, autoreglib, fluidlogged, quark, extrautils2, creativecore, ironchest, phosphor, ruins, crafttweaker, inventorytweaks, naturescompass, buildcraft, leafdecay, codechickenlib, advancedsolars, patchouli, littleframes, unidict, betterpingdisplay, twilightforest, cofh, randompatches, bookshelf, forgelin, ctm, futuremc, aether

I may have missed some, I don't think I did though.

**Comment by SlayerTheChikken** [comment]
Fluidlogged API v1.9.0.6 and Railcraft v12.0.0 conflict and cause the bottles to turn into uncraftable potion when picking up water.
