### ISSUE TITLE
Any default block placed in Betweenlands' Swamp Water instantly breaks.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Fluidlogged-API#114]
**Describe the bug**
Title.

**To Reproduce**
Place any default block this mod supports into some swamp water. See it instantly vanish.

**Expected behavior**
The default block becoming fluidlogged.

**Screenshots**
GIFs are not supported on GitHub due to their size. Here is a Dropbox link for it.
https://www.dropbox.com/s/0lgiyy39ps1hss1/javaw_LOd5xPv4Ji.gif?dl=1

**Logs**
No errors occur.

**Additional context**
N/A

**Comment by jbredwards** [comment]
I can't recreate this with the latest version, feel free to reopen if this is still an issue

**Comment by jbredwards** [comment]
found code that suggests this is still a problem, that code will be fixed next version

**Comment by jbredwards** [comment]
fixed in v1.9.0.0
