### ISSUE TITLE
Fluidlogged API is causing cascading worldgen lag when generating a fluidlogged block

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#115]
**Describe the bug**
When generating chunks with a lot of blocks that generate fluidlogged, there is a noticeable lag.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install
   - [Fluidlogged API](https://www.curseforge.com/minecraft/mc-mods/fluidlogged-api/files/3851192) - v1.8.1c
   - [Greenery](https://www.curseforge.com/minecraft/mc-mods/greenery/files/3892341) - 1.9
   - [Shadowfacts' Forgelin](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin) (Dependency)
 2. Create a world
 3. Generate new chunks of the ocean biome

**Logs**
[latest log](https://gist.github.com/juraj-hrivnak/fc65c89ca5d7e77e37e85cf82a8c7242)
[spark profile](https://spark.lucko.me/sJSze9JM0z)

**Additional context**
As I am the author of Greenery, I firstly thought it was an issue from my side, so I tried to optimize the world generation, as possible.
But after doing so, the cascading worldgen lag remains, even though Greenery uses no methods from it when generating the kelp.

So I think the problem is somewhere in the [`world#setBlockState`](https://github.com/CleanroomMC/Fluidlogged-API/blob/1.12.2-v1.7-Rewrite/src/main/java/git/jbredwards/fluidlogged_api/mod/asm/plugins/ASMHooks.java#L1597) method that Fluidlogged API is altering. Maybe there should be somewhere another area loaded check?

**Comment by jbredwards** [comment]
fixed in v1.8.1d
