### ISSUE TITLE
Betweenland's swamp water can't create source block

### ISSUE THREAD

**Issue by Pkyd** [jbredwards/Fluidlogged-API#118]
**Describe the bug**
With Fluidlogged-API in the instance, Betweenland's swamp water no longer to create a new source block when 2 water block met. It will act normally when  Fluidlogged-API is removed

**To Reproduce**
1. Install Fluidlogged-API-v1.8.1d-mc1.12.2.jar + The Betweenlands v3.8.1
2. Make a 3x1 water spawner
3. Put 2 swamp water source block on the side

**Expected behavior**
A new source block is create in the middle

**Comment by jbredwards** [comment]
fixed in v1.9.0.0
