### ISSUE TITLE
Fluids go missing texture when Streams mod is installed

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#12]
When updated from Fluidlogged API `1.4` to `1.42`
![2021-06-25_13 35 18](https://user-images.githubusercontent.com/71150936/123419431-8102a680-d5ba-11eb-8124-73953833f999.png)
![2021-06-25_13 35 07](https://user-images.githubusercontent.com/71150936/123419894-16059f80-d5bb-11eb-812d-af5cd58f9e01.png)

- Can confirm that without Fluidlogged API, there is no error.
![2021-06-25_13 46 03](https://user-images.githubusercontent.com/71150936/123420381-ca072a80-d5bb-11eb-88dc-0e4df687de57.png)

**Comment by jbredwards** [comment]
I can't recreate this issue, perhaps try removing some mods to see if it's the result of a confliction

**Comment by juraj-hrivnak** [comment]
Sorry for the late reply. 
Yes, I will try to reduce my modlist.

Also, tried the `1.4` version again, and it's working without the bug. But, after joining the world, I got a crash.
Here is the crash report: https://paste.dimdev.org/fimemukizi.mccrash

**Comment by juraj-hrivnak** [comment]
- Also, this is my latest.log
https://paste.ee/p/w7im7
_Using the `1.42` version._

**Comment by juraj-hrivnak** [comment]
Ok, **found out exactly what mod is causing this.** It is:
1. [The **Streams**](https://www.curseforge.com/minecraft/mc-mods/streams)
2. [And the **Farseek**](https://www.curseforge.com/minecraft/mc-mods/farseek)

Hope that you will be able to fix it! :D

**Comment by jbredwards** [comment]
fixed in v1.4.3!
