### ISSUE TITLE
Minecraft does not run with certain versions

### ISSUE THREAD

**Issue by ElLiox** [jbredwards/Fluidlogged-API#121]
First of all i apologize for my bad english

For some reason when opening Minecraft in the launcher, if any versions of the mod with a name ending in a letter are present (1.8.1b, 1.8.1c, 1.8.1d, 1.8.1e)
The game simply does not open, it does not release any crash message, nothing, besides it does not allow me to reopen the launcher, the only solution is to force it to close through the task manager

To make sure it was a problem with the mod, I tried to remove all the mods I had and just use Fluidlogged API
Minecraft only opened once I changed to version 1.8.1 (without any letter)

Finally, I install the latest version to date (1.8.1e) and just removed the "e" and everything worked just fine

I didn't see anyone else submit this issue, so i assume its not a constant error
But I suggest avoiding letters in version names to avoid these kind of errors

**Comment by KorewaLidesu** [comment]
Any logs available?
`latest.log` ,`debug.log`, etc.

**Comment by ElLiox** [comment]
None

**Comment by jbredwards** [comment]
This is probably the strangest bug I've ever seen for this mod lol.

I can't reproduce this myself, but I can do what you said and change the version naming criteria to only use numbers at the end instead of letters for all future releases of the mod, since it doesn't really matter imo.
