### ISSUE TITLE
Sponge incompatibility - Pt 2

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#122]
This looks like pt2 of #92  , [here](https://gist.github.com/Druwan-ctrl/d203e7d1514240ec80cb95cee7ef5ff8) is the debug log. 

I confirmed that's your mod that causes the issue, probably it's a residue of the removal of mixins, but i had a pause from mc and didn't notice (more like ragequitting, yours and 2 other mods extensively used in my server had issues). I hope it's easy to fix, can't wait to continue building!

**Comment by Druwan-ctrl** [comment]
Thanks for the fix! Is there a way I can help you test it before the release?

**Comment by jbredwards** [comment]
Unfortunately not atm, the current source code doesn't run. If you were to try running it now there would be lots of class not found errors. It will run when I'm done reorganizing the asm plugins (doing this to make the source code somewhat readable lol). I'm planning on releasing the update soon after the asm plugins are done (shouldn't be too long now)

**Comment by jbredwards** [comment]
fixed in v1.9.0.0, sorry for the wait 😅
