### ISSUE TITLE
Water physics?

### ISSUE THREAD

**Issue by Xikaro** [jbredwards/Fluidlogged-API#123]
Is it possible to add water physics in the future?

It would be very beautiful, as well as functionally expand the mod

**Additional context**
https://www.curseforge.com/minecraft/mc-mods/water-physics-overhaul

**Comment by jbredwards** [comment]
This is a cool idea, but unfortunately out of the scope of fluidlogged api. It would also probably be better as a separate mod for compatibility reasons. Fluidlogged api is a library mod, and adding this sort of functionality would break all mods that use this one as a dependency.
