### ISSUE TITLE
[SUGGESTION] Destroy burnable lavalogged blocks

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#125]
**Is your feature request related to a problem? Please describe.**
This looks a bit goofy being able to lavalogg leaves:
![2022-11-10_20 35 05](https://user-images.githubusercontent.com/9884180/201190139-88fec229-9965-46c0-9dde-ec094668a1a3.png)

**Describe the solution you'd like**
A config that when enabled will allow blocks that are lavalogged (or fluidlogged with a liquid that burn or catch things on fire) and are burnable (fenches, wooden stairs, etc.) will eventually be destroyed and just leave the fluid behind.

**Describe alternatives you've considered**
Right now I have to blacklist every block that would melt in my pack to not allow lava (or hot fluids from my "hot" group) to be fluidlogged with those fluids.

**Comment by jbredwards** [comment]
added in v1.9.0.0

**Comment by H-QueerCoded** [comment]
In 2.2.7 this isn't working as intended when switched on in the config
![2024-01-13_19 42 26](https://github.com/jbredwards/Fluidlogged-API/assets/37481947/68e68337-f926-4172-b56c-44e40a6baf28)
