### ISSUE TITLE
Fluidlogged crashes with Chiseled me

### ISSUE THREAD

**Issue by JustLookingAroundt** [jbredwards/Fluidlogged-API#126]
Hey,
I recently made a Modpack with both mods in it.
The Modpack crashed with Fluidlogged and I thought with mod crashes with Fluidlogged. 
So i was putting out some mods and find out which mod crashes with Fluidlogged. 
It was the mod "Chiseled Me".
I hope you can fix it maybe.

**Comment by jbredwards** [comment]
fixed in v1.9.0.0
