### ISSUE TITLE
Sponge incompatibility: The Return of the Crash (Pt 3)

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#128]
Hate me by now, sure am I. 

Had problems as per [122](https://github.com/jbredwards/Fluidlogged-API/issues/122), and when I saw the email I jumped on the update to test it, but as you can imagine it still can't boot. [Here ](https://gist.github.com/Druwan-ctrl/f33e0e87603ad63ed11cc639f6e828fa)is the new debug log. I just want to say that I admire your work and the fact that you actively update and include new features, keep it up!

**Comment by jbredwards** [comment]
Fixed in v1.9.0.1 (hopefully for the last time lol). Also I don't hate you at all, I'm actually grateful you're reporting these :)
