### ISSUE TITLE
Crash on creating and entering world with Electroblob's Wizardry

### ISSUE THREAD

**Issue by ChromaPIE** [jbredwards/Fluidlogged-API#129]
**Describe the bug**
Server side crash on entering a newly generated world. Problem seems to be introduced by the latest Fluidlogged API (v1.9.0.0), not present in the last version.

**To Reproduce**
1. Have both Fluidlogged API and Electroblob's Wizardry in the mods folder
2. Boot the game and create a new world
3. Crash on the server side (report: https://mclo.gs/voHcLDs)
4. You can re-enter the world (at least seemingly) just fine, but expect occasional sudden freezes (report: https://mclo.gs/g76Jhlm)

**Expected behavior**
Crash resolved for good.

**Comment by jbredwards** [comment]
fixed in v1.9.0.1
