### ISSUE TITLE
Gray water in Thaumcraft's Crucible when installed with Aqua Acrobatics

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Fluidlogged-API#131]
A few months ago, I noticed when Fluidlogged API is installed with Aqua Acrobatics it would cause the water in the Crucible to use the gray water texture instead. After updating to the latest rework it still occurs, but I'm not sure if it affects anything else outside of the Crucible. It works as intended without the API.
![Crucible](https://user-images.githubusercontent.com/86805568/204201794-e89c75d8-59ed-4634-87f9-9458bbf0ea23.png)
![CrucibleGray](https://user-images.githubusercontent.com/86805568/204201827-c129f3bc-3419-4f4e-9089-89628e0d0367.png)

**Comment by jbredwards** [comment]
This mod doesn't do anything that would influence block colors, nor does it change any textures. This is likely an aqua acrobatics bug, since that mod is what changes the water texture to be greyscale

**Comment by embeddedt** [comment]
This is fixed in Aqua Acrobatics 1.15.1.

**Comment by Turkey9002** [comment]
Thank you a lot! I really appreciate the time taken for the fix. :)
