### ISSUE TITLE
"Exception while ticking a block" with Biomes O Plenty fluids

### ISSUE THREAD

**Issue by wed15** [jbredwards/Fluidlogged-API#132]
**Describe the bug**
Trying to place down (not waterlogging) any fluid blocks from BOP causes weird behavior, eventually crashes game. I don't know what exact point makes minecraft crash, it feels like bit random. On my personal modpack crash happens almost immediately after I try to interact on position where BOP fluid didn't properly placed.  I'm not sure if this problem is only for BOP, but other modded fluids I tested (Twilight Forest, Stygian end) behaved perfectly fine.

**To Reproduce**
1. Install BOP and Fluidlogged-API on same instance.
2. Grab any Fluid bucket from BOP
3. Attempt to place the fluid block in world
4. Crash (eventually)

**Videos**
https://imgur.com/a/0foBzra
The issue recreated on instance with Fluidlogged-API and BOP installed, game crashes at the end of the video.

**Logs**
[crash.log](https://gist.github.com/wed15/b9d09460191f5e7f655ff50106f66250)
[debug.log](https://gist.github.com/wed15/086ee290ac4c74cdfedc9c3ce31d2c68)

**Additional crash logs**
[1](https://gist.github.com/wed15/adeb31d1eb58044a4d993c9c7694ba3d)
[2](https://gist.github.com/wed15/bbc861a8cff104fba55bbf0262cc83e1)
These crash logs are generated when encountered this issue (and tried to fix) on my personal modpack. Added as crash descriptions are different from the logs from video footage.

**Mod Version**
Fluidlogged-API v1.9.0.1
BiomesOPlenty-1.12.2-7.0.1.2445-universal
Mixinbooter-5.0

**Comment by jbredwards** [comment]
fixed in v1.9.0.2
