### ISSUE TITLE
Water goes completely invisible when reloading resource packs in the latest version

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Fluidlogged-API#133]
In the latest version, when changing resource packs or reloading it by pressing F3 + T. It makes all the water go invisible until you restart the game. It doesn't occur and works fine in v1.9.0.1 and I've tested this with no other mods.
![InvisibleWater](https://user-images.githubusercontent.com/86805568/204446812-fb35564f-eb70-48f7-8a20-12484a649f05.png)

**Comment by jbredwards** [comment]
fixed in v1.9.0.3
