### ISSUE TITLE
Compat issue with FoamFix / MAGE (Graphical Tweaks) (caught by CCL)

### ISSUE THREAD

**Issue by brisingraerowing** [jbredwards/Fluidlogged-API#137]
**Describe the bug**
Exceptions constantly thrown when rendering water with Foam Fix installed.

**To Reproduce**
1. Install this mod with foam fix and Mage (and CodeChicken Lib)
2. Go into a world with water
3. Observe CCL messages in chat and exception logs in the log.

**Expected behavior**
No errors

**Screenshots**
N/A

**Logs**
[Game Log](https://gist.github.com/brisingraerowing/89fb9edc06bd06b21b15b94dd93cb68e)

**Additional context**
[MAGE](https://www.curseforge.com/minecraft/mc-mods/mage)

**Comment by jbredwards** [comment]
fluidlogged api is incompatible with mage, since they both change how vanilla fluids are rendered. There's no way to resolve this from my end unfortunately since mage hides its classes from asm transformers
