### ISSUE TITLE
Start crash

### ISSUE THREAD

**Issue by HuangAdam** [jbredwards/Fluidlogged-API#138]
**Describe the bug**
Crash in start stage

**To Reproduce**
1. Start game
2. Wait a few seconds
3. Crash

**Expected behavior**
Start game

**Screenshots**
No screenshot

**Logs**
[latest.log](https://github.com/jbredwards/Fluidlogged-API/files/10299722/latest.log)
[crash-2022-12-25_17.25.51-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/10299723/crash-2022-12-25_17.25.51-client.txt)

**Additional context**
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2860
Other mod: spongeforge-1.12.2-2838-7.4.8-RC4142.jar, AdvancedRocketry-2.0.0-13.jar, AsmodeusCore-0.0.31.jar, Galacticraft-4.0.4.jar, GalaxySpace-2.0.19.jar, LibVulpes-0.4.2-25.jar

**Comment by jbredwards** [comment]
fixed in v1.9.0.6

**Comment by HuangAdam** [comment]
Thanks!
