### ISSUE TITLE
[Bug]1.9.0.6 unable to launch

### ISSUE THREAD

**Issue by ghost** [jbredwards/Fluidlogged-API#139]
1.9.0.5 works well.

**Logs**
https://mclo.gs/5aca1uG

**Additional context**
I have too many mods,so I can't tell which one cause the problem

By the way 1.9.0.5 also crash with Corail Tombstone.And here is the crash report https://mclo.gs/ntJgtcS
I don't try 1.9.0.6 with Corail Tombstone at all.

**Comment by jbredwards** [comment]
fixed in v2.0.0
