### ISSUE TITLE
[Bug] Crash On Startup

### ISSUE THREAD

**Issue by ERRORCODE509** [jbredwards/Fluidlogged-API#140]
**Describe the bug**
Game is unable to launch with this mod installed.

**Logs**
[debug.log](https://mclo.gs/oZfzHie)

**Additional context**
This is _definitely_ some kind of mod incompatibility, though I'm not sure what mod is causing it. [Here's my modlist](https://pastebin.com/PDUVDqt4).

**Comment by DanieltheGentleman** [comment]
I had the exact same issue today coming back and adding to an old pack, the game wouldn't even show up. However, the sun.reflect line made me suspicious of Optifine. Going back I read the page stating it was compatible with Optifine G5+, while I was still using F5 from 2020. Reading your mod list, you are doing the same.

After updating optifine to G5, my game and server both launch correctly. I guess it explains why the server had no issues to begin with; it has no optifine installed.

**Comment by jbredwards** [comment]
closing this, if the crash still happens when you update optifine to G5 feel free to reopen the issue :)
