### ISSUE TITLE
Only source blocks can fluidlog(?)

### ISSUE THREAD

**Issue by lazarusgreen** [jbredwards/Fluidlogged-API#142]
Ran into an odd issue in the latest version of the mod, much to my dismay.

Fluids cannot flow through fluidloggable blocks, but sources can be placed in fluidloggables and those will flow just fine - provided they're not further blocked.

![image](https://user-images.githubusercontent.com/61564109/210107820-02cd677a-308d-4708-9a45-12657b6fcc56.png)

Exception: fluidloggable blocks will become fluidlogged by flowing fluids, but only if flooded from above. HOWEVER, this spawns a fluid source block in the block that has been flooded.

![image](https://user-images.githubusercontent.com/61564109/210107967-64f3c062-2571-48ef-85e4-171bb456ffb9.png)
![image](https://user-images.githubusercontent.com/61564109/210107993-7f266490-8fac-4135-9a2c-4857a726fd18.png)
![image](https://user-images.githubusercontent.com/61564109/210108025-fa347717-d65c-43bf-9254-00d68daf561a.png)

Only fences are used in the example screenshots, however I assure this occurs with pretty much every fluidloggable block, vanilla or modded, and no matter what fluid is used. The only difference is that fluids which cannot infinitely regenerate their sources will not fluidlog even when flooding from above.

**Comment by jbredwards** [comment]
this is intentional, I was thinking about adding the ability to fluidlog non-source blocks a while ago, but decided not to since there would be a lot of weird oddities
