### ISSUE TITLE
Electroblob's Wizardry Magic Light block incompatibility.

### ISSUE THREAD

**Issue by GrandeMalum** [jbredwards/Fluidlogged-API#147]
**Describe the bug**
"ebwizardry:magic_light" block from Electroblob's Wizardry suffocates player standing inside of it while FluidloggedAPI is installed. Blacklisting the block from the configs didn't help.

**To Reproduce**
1. Install both mods.
2. Summon "/setblock ~ ~ ~ ebwizardry:magic_light" block and enter it (the block should be placed on player's eye level, not on the ground).
3. See missing texture on screen and getting suffocation damage if survival mode is on.

**Expected behavior**
I expected to enter the block like it would've worked without FluidloggedAPI, without missing texture on my entire screen and without getting damaged from suffocation, like if I was inside air block.

![2023-01-19_19 31 18](https://user-images.githubusercontent.com/6556646/213499281-6af75976-0b9d-4fbc-b6ac-839900f58285.png)
![2023-01-19_19 31 21](https://user-images.githubusercontent.com/6556646/213499300-7d349d53-19aa-48dd-b49a-de6e6278681c.png)

**Comment by jbredwards** [comment]
fixed in v2.0.0
