### ISSUE TITLE
Uncraftable potion when trying to pick up water with bottle.

### ISSUE THREAD

**Issue by SlayerTheChikken** [jbredwards/Fluidlogged-API#148]
**Describe the bug**
Fluidlogged API v1.9.0.6 and Railcraft v12.0.0 conflict and cause the bottles to turn into uncraftable potion when picking up water.

**To Reproduce**
Craft bottle, right click water with both mods installed.

**Expected behavior**
Water bottle, not uncraftable potion.

**Additional context**
Tekxit 3.14 v1.0.91

Other mods report here https://github.com/Railcraft/Railcraft/issues/2100
Additional research info here https://github.com/jbredwards/Fluidlogged-API/issues/113

**Comment by SlayerTheChikken** [comment]
While this is not a real fix you can set B:handleBottles to false in railcraft/railcraft.cfg to get around the issue.

**Comment by SlayerTheChikken** [comment]
On Railcrafts side the offending code is called here 
https://github.com/Railcraft/Railcraft/blob/6e582576808f17877fd7ed81ba5884295f9c4365/src/main/java/mods/railcraft/common/fluids/ItemFluidContainer.java on line 44 and it's link is here 
https://github.com/Railcraft/Railcraft/blob/6e582576808f17877fd7ed81ba5884295f9c4365/src/main/java/mods/railcraft/common/fluids/CustomContainerHandler.java

**Comment by jbredwards** [comment]
fixed in v2.0.0

**Comment by SlayerTheChikken** [comment]
Thank you
