### ISSUE TITLE
Doesn't seem to react well with Thaumcraft

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Fluidlogged-API#149]
**Describe the bug**
I've noticed there's lag spikes when installed with Thaumcraft and having a lot of submerged plant blocks. From testing, I believe it's the aura system causing it because it does have known issues with lag during generation. Since that mod is not maintained anymore though, I'm not sure if anything can be done about that issue.

**To Reproduce**
1. Install both Thaumcraft, Fluidlogged API and any mod that adds submerged plant blocks
2. Explore around places like the magical forest biome (due to high aura) or mountains or oceans
3. After a few minutes you'll notice a lot of lag

**Comment by jbredwards** [comment]
can you use something like [spark](https://www.curseforge.com/minecraft/mc-mods/spark) to send a profile once the lag starts to occur?

**Comment by Turkey9002** [comment]
So after a lot more testing. Seems like Universal Tweaks is the actual source of a lot of the huge lag spikes, I updated it to the most recent version and it seems to not occur as much as it used to (I might have to test it even more)? I'm not sure exactly what tweak was causing it though but I'll report this to their side as well in case

[Spark Profile with Subaquatic + Thaumcraft](https://spark.lucko.me/tZAoXiQtUm)
[Spark Profile with Subaquatic + Thaumcraft + Universal Tweaks](https://spark.lucko.me/FpaKBmYq0B)
[Same as above but with latest Universal Tweaks version](https://spark.lucko.me/lpem1GgrJY)

**Comment by Turkey9002** [comment]
@jbredwards
New update of the mod (v2.0.0) fixed the issues I had!
