### ISSUE TITLE
xemnes's crash (moved from issue#8)

### ISSUE THREAD

**Issue by jbredwards** [jbredwards/Fluidlogged-API#15]
hmm went ahead and tried out your pr, i found that i couldnt build it due to this gradle error

> Build file 'E:\.minecraft\realmofstorms\source files\MageMC\build.gradle' line: 130
> 
> A problem occurred evaluating root project 'MageMC'.
> > Could not get unknown property 'keyStore' for root project 'MageMC' of type org.gradle.api.Project.

so i removed the shadowjar block just to see if it built without it and it did.

went ahead and loaded the game up with the custom build of mage and your mod, and sadly i crashed before the game window even opened :(

there was no crash report, but i have the latest log
https://pastebin.com/ZGizfftN

im not sure what it means, not sure if its because of the modified code or not.

edit: its not, the non modified version of mage also crashes, this isnt an issue with the standalone smooth water mod.
made sure all the features except smooth water is off in the mage config too, hmmmm.

ive yet to try and see if your changes are compatible with the standalone mod. will edit if i have more info on that.

edit2: so actually, it turns out, its fluidlogged that is causing the crash, v1.4.2.

_Originally posted by @xemnes in https://github.com/jbredwards/Fluidlogged-API/issues/8#issuecomment-869078659_

**Comment by xemnes** [comment]
ive done some more tests since, installing [mixin 0.7-0.8 compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) seems to fix it

then i went and tested your fix to smoothwater/mage, but sadly that leads to a different crash caused by mixin
https://pastebin.com/XP8yVSLX

tested mage on its own (the non modified version) and it works fine

**Comment by jbredwards** [comment]
as of v1.4.3, the SmoothWater mod has been integrated with this one!

**Comment by xemnes** [comment]
nice! that pretty much solves it then, thank you. :D
