### ISSUE TITLE
Whitelist gets in the way when launching the game

### ISSUE THREAD

**Issue by aboothered** [jbredwards/Fluidlogged-API#150]
**Describe the bug**
Whenever I start the game it crashes unless I remove all the items from the whitelist at fluidlogged_api.cfg beforehand. As soon as it properly launches, I can reinsert the blocks that where listed there and it works with no problems, only to face the same problem next time I do this operation.

**Screenshots**
The current state of the whitelist
![image](https://user-images.githubusercontent.com/68480700/219712739-ea651ae8-a9ff-47dd-875b-83d91d2166d5.png)

**Logs**
[Here](https://gist.github.com/aboothered/2a43799fe974a7a17a199871eb3ff828)

**Additional context**
Also, there are some blocks that even when added to the whitelist don't get fluidlogged, as it is the case of the Kelp from the FutureMC mod. Maybe it has something to do with it being animated?

**Comment by jbredwards** [comment]
there's a missing comma on line 6 `{"blockId":"futureminecraf:hanging_lantern"}`, and an extra comma on line 7 `{"blockId":"futureminecraf:andesitestair"},`

**Comment by jbredwards** [comment]
> Also, there are some blocks that even when added to the whitelist don't get fluidlogged, as it is the case of the Kelp from the FutureMC mod. Maybe it has something to do with it being animated?

I can't find a kelp item in futuremc (not even with /give or in the source code), how did you get it so I can test this?

**Comment by aboothered** [comment]
Wow, now I feel really dumb hahahah thanks for the help!
And my apologies, I searched for the item and realized it actually belongs to "MoreBlocks", a mod that as far as I know and searched about has been only distributed inside a Discord server. Sounds really shady, but here's a link so you can download it, if you decide to xP
https://we.tl/t-Ya9T1TDi9d
