### ISSUE TITLE
[Bug] Auto-jumping when jumping on the edge of flowing water with blocks cornering on one side

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Fluidlogged-API#151]
**Describe the bug**
When jumping on the edge of flowing water with blocks cornering one side, the player will continuously auto-jump. This occurs even with auto-jump disabled.

**To Reproduce**
1. Jump on the edge of flowing water with blocks cornering either side.
2. You'll then constantly jump until you move away from that spot.

**Expected behavior**
This shouldn't occur because it does not in vanilla or without the mod installed.

**Comment by jbredwards** [comment]
fixed in v2.0.0
