### ISSUE TITLE
Crash on startup w. The Betweenlands

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#154]
**Describe the bug**
With [The Betweenlands](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod) installed and defining its' fluids in a fluidTag and using it causes a crash on startup.
```json
fluidTags: [
	{
		"id": "water",
		"fluids": [
			"minecraft:water",
			"thebetweenlands:stagnant_water",
			"thebetweenlands:swamp_water",
		]
	}
}
```

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fluidlogged API (fluidlogged_api)
Caused by: com.google.gson.JsonParseException: Fluidlogged API Config: Unable to parse fluid: thebetweenlands:swamp_water from fluidTag: water
```

If you however already have the game running and save and reload the configs it will work fine, until you relaunch the game.

In the console I can see that mods with fluids that works fine in Fluidlogged API has finished loading ..
```
...
| LCHI  | gregtech
...
```
.. but The Betweenlands is yet to finish loading.
```
...
LCH   | thebetweenlands
...
```

**Comment by jbredwards** [comment]
fixed in v2.0.0
