### ISSUE TITLE
Mobs having weird pathfinding behavior on certain type of blocks

### ISSUE THREAD

**Issue by wed15** [jbredwards/Fluidlogged-API#155]
**Describe the bug**
With FluidloggedAPI installed, mobs AI somewhat stuck on fluidlog-able blocks which have no collision(lever, button, etc) when trying to move across them. 

**To Reproduce**
1. Spawn any mob and make them move through torch or other similar blocks.
2. Watch the mob spinning

**Video demonstration (Imgur)**
https://imgur.com/a/KEQNB75

**Mod versions**
Fluidlogged-API-v2.1.0-mc1.12.2

**Comment by jbredwards** [comment]
fixed in v2.1.1
