### ISSUE TITLE
Another incompatibility with mixin (chiseled-me)

### ISSUE THREAD

**Issue by LuCa-0** [jbredwards/Fluidlogged-API#158]
**Describe the bug**
Hi,
i was trying to run Fluidlogged with chiseled-me but even with the latest version of fluidlogged it crashes on startup due to mixin not finding the classes it needs. I know compatibility isn't the most exciting thing to fix but these two mods are really irreplaceable.

**To Reproduce**
Just start the game with both latest versions of chiseled-me and fluidlogged-api

**Logs**
https://paste.ee/p/ZrbUT

Thanks in advance for the help and amazing work!

**Comment by LuCa-0** [comment]
Hi again @jbredwards ,
thank you so much for the lightning fast fix! 
The game boots fine but i sadly noticed that your patch broke this fix that the chiseled me mod included to avoid various issues.
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/54034168/226942344-f752d546-2242-4ddd-ad10-d6b1154790fa.png">
I took a look around your code but i really don't have enough experience with asm to try and fix it myself. Could you take a look to try keeping that fix about raytraceresult2 being null, even with your code that adds raytrace support for fluidlogged blocks? Thanks!

**Comment by jbredwards** [comment]
fixed in v2.2.0
