### ISSUE TITLE
issue wen opening a certain world  

### ISSUE THREAD

**Issue by hampop** [jbredwards/Fluidlogged-API#161]
**Describe the bug**
i was trying to open a old 1.8 world in to 1.12.2 and it crashed on me. it only happens on this world and I did remove fluidlogged API and it was fine the world did not crashed on me 

**To Reproduce**
1. Go to 'open a old world into 1.12.2 and you will crash'

**Expected behavior**
it crashed when opening this world only 

**Screenshots**

**Logs**
If you have access to any logs, please link them [here](https://gist.github.com/).
[crash-2023-03-25_19.50.40-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/11069942/crash-2023-03-25_19.50.40-client.txt)

**Additional context**
![image](https://user-images.githubusercontent.com/87606666/227738566-9d57669d-e44e-4fbd-817c-011dbd848458.png)
and the world file 
[JCW-.zip](https://github.com/jbredwards/Fluidlogged-API/files/11069960/JCW-.zip)

**Comment by jbredwards** [comment]
after testing this, I'm pretty sure this is unrelated to fluidlogged api. I tried loading the world with no mods installed (aside from forge), and it still repeatedly crashed
