### ISSUE TITLE
Betweenlands/Fluidlogged API Crash on latest version

### ISSUE THREAD

**Issue by Icegod101** [jbredwards/Fluidlogged-API#163]
**Describe the bug**
Ticking Entity Error for mobs entering water near blocks or aquatic mobs in general in The Betweenlands with Fluidlogging API on the latest versions of both mods.

**To Reproduce**
1. Have both Fluidlogged v2.12 and Betweenlands v3.9.5 installed on any 1.12 profile.
2. Enter The Betweenlands and go near a body of water like Sludge Plains or Deep Waters Biome.
3. Either wait or keep moving further into the biome until you freeze and CTD.

**Logs**
https://gist.github.com/Icegod101/fc465e0dc9a40db10a804decbbf4a7f8

**Additional context**
Clean fresh profile, first experienced on a large modlist that was relatively stable

New Profile has only the following mods;
Fluidlogged-API-v2.1.2-mc1.12.2
TheBetweenlands-3.9.5-universal
HadEnoughItems_1.12.2-4.24.5
NotEnoughCreativity-1.12-1.2.3

And it still experienced the same crash

Previous versions played nicely with each other

**Comment by jbredwards** [comment]
fixed in v2.2.0
