### ISSUE TITLE
[compatibility] Crash with Subaquatic and Draconic evolution

### ISSUE THREAD

**Issue by Brown-bricks** [jbredwards/Fluidlogged-API#164]
**Describe the bug**
The game produces a rendering crash when killing the Ender Dragon, caused by Draconic Evolution's dragon heart item.

**To Reproduce**
Kill the ender dragon with Fluidlogged API, Draconic Evolution and Subaquatic installed

**Expected behavior**
The Dragon Heart is rendered properly

**Logs**
[crash-2023-04-16_14.47.24-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/11243799/crash-2023-04-16_14.47.24-client.txt)

**Comment by jbredwards** [comment]
This is a subaquatic bug, not a fluidlogged api bug. However there's now a fix ready for the next subaquatic update :)
