### ISSUE TITLE
Waila/Hwyla showing vanilla fluids twice when Fluidlogged-API is installed 

### ISSUE THREAD

**Issue by xJon** [jbredwards/Fluidlogged-API#165]
Without:
![image](https://user-images.githubusercontent.com/8945347/234662509-d5b702f8-fb49-4438-b732-353a1d0b44f0.png)
With:
![image](https://user-images.githubusercontent.com/8945347/234663562-2ab7f484-c34a-4a4e-b983-a0372cbdaa16.png)
![image](https://user-images.githubusercontent.com/8945347/234663628-2172e501-ee01-45e0-82dd-b49a5be617e4.png)

**Comment by xJon** [comment]
To reproduce make sure to have `Liquids` enabled for Waila:
![image](https://user-images.githubusercontent.com/8945347/234674049-47533649-9807-4079-b55f-72163f935d54.png)

**Comment by jbredwards** [comment]
fixed in v2.2.0

**Comment by xJon** [comment]
Thank you!
