### ISSUE TITLE
Incompatibility with one "Oceanic Expanse" Block

### ISSUE THREAD

**Issue by tomygcz** [jbredwards/Fluidlogged-API#166]
**Describe the bug**
One block of "Oceanic Expanse" is not able to be fluidloggable.

**To Reproduce**
1. Put it Whitelist the block:
   - Conduit (oe:conduit)
3. Open Minecraft,
4. Put the block in question in-game.

**Expected behavior**
To log correctly the mentioned block.

**Screenshots**
![image](https://user-images.githubusercontent.com/93863909/235299333-62534c14-cde7-4885-9d5f-535cc929a466.png)

![2023-04-29_13 02 08](https://user-images.githubusercontent.com/93863909/235299348-864a51be-0a2b-4ac7-b954-8a1acc66edc6.png)

**Comment by jbredwards** [comment]
edit: fixed from oceanic expanse's side: https://github.com/SirSquidly/Oceanic-Expanse/issues/11
