### ISSUE TITLE
Fluidligged Api is not compitable with optifine G5 custom colors for water

### ISSUE THREAD

**Issue by domovishche** [jbredwards/Fluidlogged-API#167]
**Describe the bug**
Fluidlogged Api is not compitable with optifine G5 custom colors for water.

**To Reproduce**
Steps to reproduce the behavior (optifine G5 should be installed):
1. Have a resource pack with custom water colors
2. Open video settings, open quality
3. `custom colors: ON` (also does not work with other settings like `Connected textures:fancy`)
4. Select a resource pack if you haven't done this before
5. See the error

**Expected behavior**
Water should have custom colors.

**Screenshots**
with Fluidlogged Api
![2023-05-05_21 54 01](https://user-images.githubusercontent.com/132643076/236544417-4196ab9c-a587-467f-a1e5-a4f1ae77996f.png)

without
![2023-05-05_21 55 27](https://user-images.githubusercontent.com/132643076/236544619-30140aea-5865-4f66-aa1e-d6d2bab4b5c7.png)

**Logs**
Here. https://gist.github.com/domovishche/2ed2c82ebe35529754757544887b728e

**Additional context**
OptiFine G5, PassableLeaves are installed

**Comment by jbredwards** [comment]
fixed in v2.2.0
