### ISSUE TITLE
Hates Nothirium.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Fluidlogged-API#168]
**Describe the bug**
Title.

**To Reproduce**
Use both mods, make a world, run around for awhile. Game will crash randomly.

**Expected behavior**
Game to not crash.

**Screenshots**
N/A.

**Logs**
https://pastebin.com/WuRP0V9A

**Additional context**
N/A.

**Comment by jbredwards** [comment]
fixed in v2.2.1
