### ISSUE TITLE
Illegal access error for ModelManager

### ISSUE THREAD

**Issue by Jimbologo** [jbredwards/Fluidlogged-API#169]
**Describe the bug**
Upon using the API and running error occurs relating to the following...  
```
Exception caught during firing event net.minecraftforge.client.event.TextureStitchEvent$Pre@6a178850:
java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.modelManager from class git.jbredwards.fluidlogged_api.mod.client.ClientEventHandler
```
Looking into it, IT is reporting that `Minecraft.getMinecraft().modelManager` on line 43 of ClientEventHandler.java "'ModelManager' has private access in 'net.minecraft.client.Minecraft'"

It is using commit hash 9a0e692

**To Reproduce**
1. add the relative info into build.gradle for fluidlogger api
2. click on build
3. then attempt to run

**Expected behavior**
1. add the relative info into build.gradle for fluidlogger api
2. click on build
3. then attempt to run
4. See main menu

**Screenshots**
![image](https://github.com/jbredwards/Fluidlogged-API/assets/20266417/30e935e0-77ba-4b47-ab2d-313caf7bc280)

**Logs**
https://gist.github.com/Jimbologo/1d2fe8ff55297c0256e41d6316896ffe

**Additional context**
none

**Comment by embeddedt** [comment]
I see `legacydev` in your stack trace, are you using FG5? AFAIK it doesn't apply access transformers from dependencies (which causes many issues). You should probably set up [FancyGradle](https://gitlab.com/gofancy/fancygradle/-/wikis/home).

**Comment by jbredwards** [comment]
as embeddedt mentioned above, FG3+ doesn't correctly apply access transformers from dependencies, use FG 2.3 or FancyGradle
