### ISSUE TITLE
Rendering error causing "missing texture"

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#17]
This is what happens with the mod [Water Mechanics](https://www.curseforge.com/minecraft/mc-mods/bubble-column-elevator-backport)

![2021-06-27_20 50 05](https://user-images.githubusercontent.com/69646703/123556192-17d18d80-d78a-11eb-8977-e22be76eda0a.png)
![2021-06-27_20 50 02](https://user-images.githubusercontent.com/69646703/123556194-199b5100-d78a-11eb-951e-bbcfab7621ff.png)

**Comment by jbredwards** [comment]
The water mechanics mod relies on overriding the vanilla fluid renderer, which this mod scraps in place of the heavily improved forge one.

**Comment by jbredwards** [comment]
After looking more into this, the bug is actually related to the other mod replacing the vanilla fluid blocks, my bad! Your issue will be fixed next update :)

**Comment by jbredwards** [comment]
fixed in v1.4.4!

**Comment by Druwan-ctrl** [comment]
MAN, you're amazing!
