### ISSUE TITLE
Incompatibility with Mohist

### ISSUE THREAD

**Issue by vico93** [jbredwards/Fluidlogged-API#170]
**Describe the bug**
I'm reassembling my modpack for 1.12.2 with Fluidlogged API v2.2.1, and tried to run them on [Mohist](https://github.com/MohistMC/Mohist) (hybrid Forge + Spigot server), but unfortunately i got [this crash](https://gist.github.com/vico93/a75e49db17e5e8e66d2218821308a1e5) when trying to boot the server.

So i went ahead and [opened a ticket on their repo](https://github.com/MohistMC/Mohist/issues/2488), after an investigation done by @Mgazul (i sent him the whole server folder as a .zip) he determined that it's a problem on Fluidlogged API side, and Mohist can't try to fix solemny on their side.

So i decided to open this ticket here to see what can be done about it.

**Comment by jbredwards** [comment]
looks like this was just fixed from their end: https://github.com/MohistMC/Mohist/commit/aa408426a1b80c37b029f86040c3502f0700e8e3

**Comment by Mgazul** [comment]
https://github.com/MohistMC/Mohist/commit/aa408426a1b80c37b029f86040c3502f0700e8e3 Fixed this

**Comment by vico93** [comment]
Fixed! Thank you so much @Mgazul and sorry for any inconvenience @jbredwards
