### ISSUE TITLE
Fish do not spawn.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Fluidlogged-API#171]
**Describe the bug**
Title. Previous versions did not have this issue.

**To Reproduce**
Use the mod.

**Expected behavior**
Fish should spawn.

**Screenshots**
Most other creatures, such as Guardians via Quark, or Ice & Fire's aquatic mobs do spawn.
![2023-05-26_13 39 18](https://github.com/jbredwards/Fluidlogged-API/assets/51277766/aad88b4b-fea2-46af-a192-c41752bdf399)

**Logs**
N/A.

**Additional context**
N/A.

**Comment by jbredwards** [comment]
assuming this issue is meant for my other mod, [Subaquatic](https://github.com/jbredwards/Subaquatic)? This mod doesn't add fish, or touch any mob spawning mechanics

**Comment by MagmaSlime123** [comment]
Oops, sorry.
