### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AlexRover** [jbredwards/Fluidlogged-API#173]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
[crash-2023-05-31_19.44.46-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/11614885/crash-2023-05-31_19.44.46-client.txt)

**Additional context**
Add any other context about the problem here, this may include mods, plugins, etc.

**Comment by AlexRover** [comment]
The first time it crashed was when entering a new world in creative mode. The second time I created a world in survival and was able to enter by going into creative mode after a while the world collapsed when loading new chunks

**Comment by jbredwards** [comment]
fixed in v2.2.3
