### ISSUE TITLE
Some water blocks next to ice don't render properly

### ISSUE THREAD

**Issue by xJon** [jbredwards/Fluidlogged-API#174]
**To Reproduce**
1. Install Subaquatic, Fluidlogged API, and their dependencies
2. Open a new world with seed `1943964198158727210`, go to coordinates `4320, 63, 187`
3. See issue next to some of the naturally generating ice, or when breaking ice next water

**Screenshots**
![image](https://github.com/jbredwards/Fluidlogged-API/assets/8945347/aa0d607d-1559-4bf2-b216-4b802ecddcea)
![image](https://github.com/jbredwards/Fluidlogged-API/assets/8945347/dd281636-4db6-4368-982c-1f739b3e37ce)

Also, as the world loads this can appear:
![image](https://github.com/jbredwards/Fluidlogged-API/assets/8945347/6b0408b3-5554-4105-88ba-97889b242122)

**Comment by jbredwards** [comment]
fixed in v2.2.4
