### ISSUE TITLE
weird rendering issue with fluids

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#176]
**Describe the bug**
getting a weird rendering problem with fluids, unsure whats causing it as it seems to be very random on when it happens but i have narrowed it down to a select few mods, heres some images:
https://i.imgur.com/HM5Lk97.png
https://i.imgur.com/VOCxSSA.png

edit: on first load of a world, i notice that theres this extra face on fluids too, but can only be seen from below, has now backface above:
https://i.imgur.com/dOR854w.png

list of mods i have installed:
https://i.imgur.com/biJrLtI.png

i can enter a world and water appears to be fine, fly around for a bit, and sometimes fluids just suddenly end up rendering weird.
faces may be missing, or the back side of the fluid will be z-fighting with the blocks next to it.

**To Reproduce**
unsure how to reproduce

**Comment by jbredwards** [comment]
fixed in v2.2.5
