### ISSUE TITLE
#176 issue: weird rendering is still happening

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#179]
hello, randomly encountered the rendering issue again, sadly seems its still a problem. again intermittent, sometimes it happens, sometimes it doesnt. and there appears to be unnecessary faces on the angled model too
![image](https://github.com/jbredwards/Fluidlogged-API/assets/603338/62298149-4bf3-455b-8f2f-6a38d6b6be68)
![image](https://github.com/jbredwards/Fluidlogged-API/assets/603338/d4dda681-7bb8-4a31-9ff0-70e52794fd98)

**Comment by jbredwards** [comment]
Fixed in v2.2.6 (hopefully for the last time lol). I replaced Forge's fluid renderer, so let me know if you find any new problems :)

**Comment by xemnes** [comment]
thanks will do
