### ISSUE TITLE
Batching chunks - world startup crash

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#18]
- I have a similar issue to #14.
The **crash** happens when **loading an existing world**, but there is a different crash:
- ` Fluidloged API 1.4`: https://paste.dimdev.org/kewaparowi.mccrash
- ` Fluidloged API 1.43`: https://paste.dimdev.org/kazalanuqo.mccrash
  - `Fluidloged API 1.4, latest.log`: https://paste.ee/p/501rd
  - Without Fluidloged API, there is no crash.
***
This happened to my world that used to have the Fluidloged API installed. Then I removed it because of #12.
And then when I **added the mod back**, both versions `1.4` and `1.43` crashed.
The crash happens a few seconds after joining the world, so I move around a little bit and then boom, crash.
![2021-06-25_13 46 03](https://user-images.githubusercontent.com/71150936/123786124-a0ab0f00-d8d9-11eb-802d-945ce50d69d8.png)

**Comment by jbredwards** [comment]
fixed in v1.5!
