### ISSUE TITLE
Waterlogging Plants?

### ISSUE THREAD

**Issue by ghost** [jbredwards/Fluidlogged-API#180]
Attempting to add plants (e.g. grass, or any flowers, both vanilla and modded) to the whitelist in the config causes a crash on startup. 

There's not much more to say about it other than it causes a crash, and would be cool to see working. This feature would just be something cool, even if most people wouldn't really use it, but could also enhance compatibility with mods that add water plants (e.g. plant mega pack, biomes o plenty, etc. etc.)

**Comment by jbredwards** [comment]
can you send the log? (using something like [mclo.gs](https://mclo.gs))

**Comment by ghost** [comment]
> 

sure! here's the log:
https://mclo.gs/IOro8nd
it's a clean instance of 1.12.2 with no other mods installed. the mod works fine if i don't add tallgrass to the whitelist config. i thought i added it to the config wrong, so i replaced it with a solid block and that worked?

**Comment by jbredwards** [comment]
this is very late, but it looks like a malformed config file (run the file through a [JSON Validator](https://jsonformatter.curiousconcept.com) to find the error)
