### ISSUE TITLE
v2.2.6 is incompatible with Aqua Acrobatics

### ISSUE THREAD

**Issue by domovishche** [jbredwards/Fluidlogged-API#181]
v2.2.6 is incompatible with Aqua Acrobatics (tried v1.15.1 - 1.15.3), while v2.2.5 works fine. Using mixinbooter or mixinCompact or MixinBootstrap doesn't affect anything. 

Here's log for v2.2.5: [latest.log](https://github.com/jbredwards/Fluidlogged-API/files/12291503/latest.log)
For v2.2.6: [latest.log](https://github.com/jbredwards/Fluidlogged-API/files/12291513/latest.log)

**Comment by jbredwards** [comment]
fixed in v2.2.7
