### ISSUE TITLE
Fluidlogged-API-v1.4.3-mc1.12.2 Problems with the water

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#19]
Hi,
I have testet your new Update and have a bug found what not good ist and okay the water is in the world but you can it not see then you not diving in the water. Show the 2 Pictures the 1 is the Problem what we have and the other is by diving in water who the water normal is. Please fix it in the next version. I have this testet in flatworld and this looks so in the Pictures and in a normal World is it the same. I hope you find the bug and can fix it . Picture 3 is in a normal World make. All pictures was in a day not night. 
![2021-06-29_18 20 32](https://user-images.githubusercontent.com/42325138/123833947-2d1ff680-d907-11eb-8611-f032530cb497.png)
![2021-06-29_18 20 35](https://user-images.githubusercontent.com/42325138/123833959-30b37d80-d907-11eb-8733-c4fa89fe87c8.png)
![2021-06-29_18 27 56](https://user-images.githubusercontent.com/42325138/123834523-cb13c100-d907-11eb-98d4-1067eea49cb1.png)

The Hud in down right is from a other mod what a Parcour mod is with the Green line.

**Comment by jbredwards** [comment]
I can't recreate this issue. What other mods do you have installed?

**Comment by Titoo8899** [comment]
I have this mods:

https://www.curseforge.com/minecraft/mc-mods/decocraft
https://www.curseforge.com/minecraft/mc-mods/ptrlib
https://www.curseforge.com/minecraft/mc-mods/the-time-stop-mod
https://www.curseforge.com/minecraft/mc-mods/hide-hud-util
https://www.curseforge.com/minecraft/mc-mods/parcool
https://www.curseforge.com/minecraft/mc-mods/tickratechanger
and your mod and all Mods have I in the newest Version what the Creater have and I play with 
Forge: 1.12.2 - 14.23.5.2855 and have by my Options 12GB of Ram by my 32 GB Ram what I have

**Comment by Titoo8899** [comment]
I hope you can with this and your mod the Problem find the First is a Deco mod and time stop is a cool time stop and slow motions mod hide hud is a command what can make invisible the Armor,arm and other huds the parcool is a parcour mod and the tickratechanger is a mod what only with the time stop mod work and ptrlib is a core mod for decocraft

**Comment by Titoo8899** [comment]
A i have found the Mod what not work with your mod the 
https://www.curseforge.com/minecraft/mc-mods/the-time-stop-mod
https://www.curseforge.com/minecraft/mc-mods/tickratechanger
with this 2 mods is the bug on but then I this 2 mods deleted when is the water normal and the bug is off

**Comment by Titoo8899** [comment]
I have the other people write and I hope you and the creator of the time stop find a way for fix this

**Comment by Titoo8899** [comment]
Hi, good news the new Version 1.4.4 have fix my Problem. It was the think from issus 17
