### ISSUE TITLE
Cobble gen

### ISSUE THREAD

**Issue by Thomasdeontdeker** [jbredwards/Fluidlogged-API#192]
I play a modpack with this mod installed.
When i try to make the vanilla (waterlogged  version 1.13) stairs cobble gen, it does not work the way it does in the newer version.

I would like that this interaction works the same as the vanilla version

![image](https://github.com/jbredwards/Fluidlogged-API/assets/83987733/12676997-52f7-4ecd-9fce-15dacacd201b)

I hope i have given enough information and hope that it does get implemented

Greeting
Thomas

**Comment by jbredwards** [comment]
this is intentional, and fixes [MC-127108](https://bugs.mojang.com/browse/MC-127108). In the future I may add a config option for this though :)
