### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by jorgestudios** [jbredwards/Fluidlogged-API#195]
https://privatebin.net/?e39831d83e8aaab9#HC2bXx3tehRNWTpHCfzLuYfy72XFMbNzChjtzdmcqRUP

**Comment by jbredwards** [comment]
remove optifine F4

*(I'm uploading the log to mclo.gs [here](https://mclo.gs/xAYCkWJ) in case this issue is visited again after the privatebin link expires)*
