### ISSUE TITLE
.notifyNeighboringFluids crash / EBWizardry crash [v2.2.7] [crash]

### ISSUE THREAD

**Issue by Sethgno** [jbredwards/Fluidlogged-API#196]
**Describe the bug**
null error when placing electroblobswizardry "Spectral Dust" into the receptacle on an imbuement altar only while any stairs block is placed next to it. (there may be other blocks that cause this)
- under same conditions, causes spectral dust to duplicate when interacting with receptacles
- under same conditions, game will crash when imbuement of a "Ruined Spell Book" finishes

**To Reproduce**
**1 -** have Fluidlogged-API-v2.2.7 and ElectroblobsWizardry-4.3.12 installed
**2 -** place an EBW "Imbuement Altar"
**3 -** crouch-place 4 EBW "Receptacle" on each side of the altar
**4 -** place any "Stairs" block next to one of the receptacles
**5 -** right-clicking that receptacle while holding "Spectral Dust" will send these errors:
- _java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Exception while updating neighbours_
- _Caused by: java.lang.NullPointerException at git.jbredwards.fluidlogged_api.mod.asm.plugins.vanilla.block.PluginBlockStairs$Hooks.notifyNeighboringFluids(PluginBlockStairs.java:50) ~[PluginBlockStairs$Hooks.class:?]_

(full error below)
**6 -** placing 4 "Spectral Dust" into the receptacles and placing a "Ruined Spell Book" into the altar will begin the imbuement process and cause a crash
(full crash log below)

**Expected behavior**
spectral dust should not duplicate when interacting with an altar next to stairs
game should not crash when imbuement altar finishes imbuing

**Screenshots**
![2024-01-04_12 24 31](https://github.com/jbredwards/Fluidlogged-API/assets/131620592/2025e362-786d-495f-86d9-77f6d82729b9)
[imbuement altar during imbuement process, positioned next to stairs]
(screenshot taken from a larger modded instance, but also tested with just these two mods)

**Logs**
full error - https://gist.github.com/Sethgno/d8135c0d0498b1122497ed162e6dc4bc
full crash log - https://gist.github.com/Sethgno/9e5783832705e1ae984073087248d9ad

**Comment by jbredwards** [comment]
this issue is not caused by fluidlogged api
