### ISSUE TITLE
VintageFix Mixin Crash

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Fluidlogged-API#199]
**Describe the bug**
Title.

**To Reproduce**
Start the game with this mod and MixinBooter.

**Expected behavior**
The game to boot.

**Screenshots**
N/A

**Logs**
The error itself: https://pastebin.com/er5t1PGU
Whole log file: [latest.log](https://github.com/jbredwards/Fluidlogged-API/files/14595208/latest.log)

**Comment by jbredwards** [comment]
this looks like a vintagefix mixin issue

**Comment by MagmaSlime123** [comment]
Not sure why MixinBooter was mentioned. Huh.

**Comment by xJon** [comment]
Should be fixed with the latest VintageFix Actions build (https://github.com/embeddedt/VintageFix/actions/runs/8282144801)

**Comment by hampop** [comment]
this is now fix so you can now close this
