### ISSUE TITLE
Request for v2.2.8

### ISSUE THREAD

**Issue by Lenvill-Jarlsen** [jbredwards/Fluidlogged-API#203]
If I may, I would like to request for the most up-to-date version of this mod to be published to Modrinth. I am a modpack dev, and I came here after having experiencing some of the issues that have already been reported, and discovered that all the ones I had encountered were marked with "fixed in dev." It has been some time since the last update was published, and having access to the fixes you have implemented since then would player experience!

**Comment by jbredwards** [comment]
I won't release the next update before it's finished. But I have been thinking about creating a "1.12.2-Indev" branch with my wip code (after I do a couple more things first) :)

**Comment by Lenvill-Jarlsen** [comment]
Very fair. I will look forward to the next release!
