### ISSUE TITLE
The log loop records errors

### ISSUE THREAD

**Issue by al-wei** [jbredwards/Fluidlogged-API#204]
https://gist.github.com/al-wei/2a1a808ed1c590d86c518e950542353f

**Comment by jbredwards** [comment]
can you post the full log? (using https://mclo.gs)

**Comment by al-wei** [comment]
> can you post the full log? (using https://mclo.gs)

I'm very sorry, I already know, I mistakenly used the old java（1.8.0_50, It seems to come from a program. The third-party initiator automatically selects java, causing trouble.）, in fact it is not a problem.
