### ISSUE TITLE
Question to the future of this mod

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#205]
Hi,
I have all the time your mod play and have so much time invest to make maps great. But I miss new Updates with new Features and Fixes. Give it in the next weeks a new Uodate of your Mod?

I hope you can give me a answer. And I hope we hear more from you in the next weeks.

**Comment by jbredwards** [comment]
I am ***extremely*** bad at predicting when updates will be ready, so I don't want to get your hopes up by saying that the next update will be ready soon. That being said, I'll commit my local code either tomorrow or the day after

**Comment by Iron-carrot** [comment]
When will you commit your local code?

**Comment by jbredwards** [comment]
> When will you commit your local code?

Already have :)
https://github.com/jbredwards/Fluidlogged-API/tree/1.12.2-Indev

**Comment by Mike74846** [comment]
I was happy then your next update is finish. I wait so long of a new Update and my Projekt of realistic Island with a smooth rivers etc. was I happy of all the new features and fixes
