### ISSUE TITLE
Update of your Mod?

### ISSUE THREAD

**Issue by Mike74846** [jbredwards/Fluidlogged-API#212]
Hi,
we all have see what you have create in the time of your live and I find it so cool. I have one little question. I build on a Project and your mod have I play so long and the last Version 2.2.7 was great. Comes this month a Update of this mod with all the Features?

**Comment by jbredwards** [comment]
> we all have see what you have create in the time of your live and I find it so cool. I build on a Project and your mod have I play so long and the last Version 2.2.7 was great.

Thank you! <3

> Comes this month a Update of this mod with all the Features?

I'm currently in college, so probably not. The only big hurdle left before the v3.0.0 release is fixing the performance of flowing fluid blocks (and online configs, but that's mostly done). I haven't had enough free time to sit down and really look into the performance issue properly and fix it, but I will have enough free time after the semester ends (in late December)

**Comment by Mike74846** [comment]
oh okay. Think you in 2025 in one of the first months come the Update 3.0.0?

**Comment by jbredwards** [comment]
Absolutely!
