### ISSUE TITLE
Incompatible with the Mod "Better Water Mesh"

### ISSUE THREAD

**Issue by Mike74846** [jbredwards/Fluidlogged-API#213]
**Describe the bug**
The Bug is a Visual Problem with your Mod Physic and the Better Water Mesh Physic what not work then all 2 Mods was load. Your Mod will work normal but the Visual effects of the "Better Water Mesh" mod will not work. I hope you can fix it.

**To Reproduce**
1. Put FluidloggedAPI V.2.2.7 Mod and Better Water Mesh (https://legacy.curseforge.com/minecraft/mc-mods/better-water-mesh) in the Mod Folders
2. Start Minecraft Forge latest version
3. Start a new Map and look the waterphysic (Please look the Pictures what I add)
4. You see the Incompatible of the 2 Physics

I have hope this new Mod and your mod work but your mod stop the animation of the other Mod. I hope you can a compatible Update make

Screenshot 1+2 was only with the Mod Better Water Mesh Mod
Screenshot 3+4 was with the Mod Better Water4 Mesh Mod and Fluidlogged API Mod make
Screenshots:
![1](https://github.com/user-attachments/assets/864403fd-fb9a-43ff-af48-790185bd3404)
![2](https://github.com/user-attachments/assets/14006dfc-b700-4196-860e-443e5d3931c9)
![3](https://github.com/user-attachments/assets/aebfb476-7285-4639-ad3f-a275ee9ce21f)
![4](https://github.com/user-attachments/assets/ca4d81b0-f9fa-4794-b006-a27a553075f6)

Mods:
- Fluidlogged API Version 2.2.7
- Better Water Mesh Version 1.0.0

**Comment by jbredwards** [comment]
This issue should be fixed from B.W.M.'s end.

Fluidlogged API effectively disables the vanilla fluid rendering system in favor of forge's far superior system. Right now B.W.M. only makes changes to the vanilla fluid renderer, so when B.W.M. adds support for forge fluids (hopefully by only transforming [`ModelFluid$BakedFluid::buildQuads`](https://github.com/MinecraftForge/MinecraftForge/blob/d3f01843f7e7a4f613b5e8113d381fd8747b4343/src/main/java/net/minecraftforge/client/model/ModelFluid.java#L284), to keep forge's fluid system), they'll also be able to apply a similar transformer to this mod's [`BakedModelFluid::buildQuads`](https://github.com/jbredwards/Fluidlogged-API/blob/e74c949725002506401b5d85925edb1d3c8775ac/src/main/java/git/jbredwards/fluidlogged_api/mod/client/model/BakedModelFluid.java#L97) for "easy" compatibility.
