### ISSUE TITLE
Fluid data not saved in reccomplex structures

### ISSUE THREAD

**Issue by ghost** [jbredwards/Fluidlogged-API#215]
**Describe the bug**
Recurrent complex is unable to save fluidlogged state of blocks because it doesn't recognize fluidstates. Unsure if this should be a feature request to add support, or a bug report.

**To Reproduce**
1. Create a structure using fluidlogged blocks
2. Export it using recurrent complex
3. Generate or re-import the structure
4. Observe lack of fluidlogging

**Expected behavior**
generated structures preserve fluidlogged data

**Comment by jbredwards** [comment]
I prefer to only add mod support from my end for mods that no longer receive updates for 1.12. Recurrent Complex was updated recently, so support for this feature should be added from their end, to ensure it doesn't break down the line with future updates.
