### ISSUE TITLE
[v1.5] Server crash

### ISSUE THREAD

**Issue by Romz24** [jbredwards/Fluidlogged-API#24]
When I try to start the server with an updated version, I get a crash. Version v1.4.4 is stable.

[crash-2021-07-08_16.27.24-server.txt](https://github.com/jbredwards/Fluidlogged-API/files/6785998/crash-2021-07-08_16.27.24-server.txt)

**Comment by jbredwards** [comment]
~~try v1.5~~ nvm will be fixed next update

**Comment by jbredwards** [comment]
fixed in v1.5.1!
