### ISSUE TITLE
Pixelbug in the new 1.5.1 of your Mod with the Rails

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#25]
Hi,
I have testet the new Support of Rails in Fluid and then I break in Creative a Rail in water it give not by all Breaks I have by all 2 or 3 Breakrail this Problem with a Pixel by the Break what the Colour purple have. I have no idear from what it comes. Is this normal from Minecraft or is this from the Support of Rails a bug? In the 2 Pictures can I good see the one Pixel the first have in the top left and the second Picture have in the central a Pixel Bug. And sorry I have it testet under the water then you click the two photos you can see the purple pixels.
![2021-07-10_22 33 54_2](https://user-images.githubusercontent.com/42325138/125175891-91786b00-e1cf-11eb-96e6-6e497708e620.png)
![2021-07-10_22 33 56](https://user-images.githubusercontent.com/42325138/125175893-94735b80-e1cf-11eb-90da-6a38f22e578f.png)

**Comment by jbredwards** [comment]
The untextured particle is a hit particle from the water. The untextured part isn't happening on my end though.

**Comment by jbredwards** [comment]
Do you have any other mods installed that could influence the particle texture?

**Comment by jbredwards** [comment]
closing this, your newer issue directly causes this one, thus when that one is fixed, this one will be as well.

**Comment by jbredwards** [comment]
fixed in v1.6!
