### ISSUE TITLE
completely opaque water (with fluidlogged api + optifine + better foliage + forgelin)

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#27]
not sure if its because im using the dev build you sent me or not. but my water is now completely opaque.
https://i.imgur.com/lwI8Qxn.png

**Comment by jbredwards** [comment]
huh weird, do the fluidlogged water blocks & modded translucent fluids do that as well?

**Comment by jbredwards** [comment]
fixed in v1.5.2! (still can't replicate unfortunately, so let me know if this is wrong)

**Comment by xemnes** [comment]
right thanks, sorry i didnt follow this up, been very busy and havent had a chance to check.

**Comment by Druwan-ctrl** [comment]
Same issue here, even with the last update. Fluidlogged-API-v1.4.4 does not have this bug

**Comment by jbredwards** [comment]
what's your mod list?

**Comment by xemnes** [comment]
heres mine https://pastebin.com/raw/4nZpufcd excluding fluidlogged api, this is from a forced crash.

**Comment by Druwan-ctrl** [comment]
This is mine: https://pastebin.com/raw/wqYM8mHd

**Comment by xemnes** [comment]
update on this issue, ive discovered that its not just water, but any block that uses the water texture. for example, aether portals (though i have forced it to use the vanilla water texture as it used a static non animated water texture, i also applied a biome tint to it). thought it mightve been optifine but disabling custom colors doesnt fix it.

edit: so it turns out it actually isnt just water, or other fluids, its every single translucent block! lol
https://i.imgur.com/cCOpGHB.png
im holding one of the blocks thats translucent in my hand, you can see to the right that its completely opaque, the purple block at the back is stained glass, next to it is another glass block from better nether.

**Comment by jbredwards** [comment]
can either of you trim your mod lists to 1 or 2 other mods? It's a lot for me to have to download, and then end up having to trim myself anyway... -_-

**Comment by xemnes** [comment]
you mean doing binary split to figure out the problem mod? i suppose i could do that. it is a lot of work but im willing to do it if it makes your life easier. i will have to do it tomorrow though.

**Comment by jbredwards** [comment]
one guy sent me his mods folder entirely so I didn't have to download them all, you could do that as well if it would be less work for you

**Comment by xemnes** [comment]
i use a custom private launcher that downloads all the mods from my private webhost for a small discord server im apart of. id have to send it to you privately as i dont want people publicly using it as im pretty sure it would break some rules. i have no idea how to privately message you on github, or if its even possible?

**Comment by jbredwards** [comment]
fixed in v1.6!

**Comment by xemnes** [comment]
ahh so it was better foliage that was the problem, i thought it mightve been unifine or something else. thank you!
