### ISSUE TITLE
Biomes O' Plenty's coral and other already waterlogged blocks gets broken by water.

### ISSUE THREAD

**Issue by Foreck1** [jbredwards/Fluidlogged-API#28]
I'm not too sure if this counts as a too specific issue, but coral and algae from Biomes O plenty get popped off from the ocean floor when Fluidlogged API is installed, even though these blocks are already waterlogged. This destroys these biomes and causes great lag due to the block updates and dropped items. 
![image](https://user-images.githubusercontent.com/47757429/126238587-99cdf923-ccab-47ab-a934-c8219eec034d.png)

**Comment by jbredwards** [comment]
this mod overrides many of the vanilla water block's behaviors, including what it can & can't flow into. It seems it thinks it can flow into the biomes o plenty coral blocks, as they don't use forge's fluid block class. This will be fixed next update

**Comment by Foreck1** [comment]
Thank you **very much** for your dedication and continued support for this mod; you actively engage with your user base and try to fix as many bugs as possible to make this such a quality mod.
I was dubitative when I first saw a mod that could backport waterlogging, but you proved us all wrong, so hats off to you and I hope Fluidlogged API keeps getting the attention it deserves!

**Comment by jbredwards** [comment]
fixed in v1.5.2!
