### ISSUE TITLE
Compatibility with Sink or Swim

### ISSUE THREAD

**Issue by Lylythii** [jbredwards/Fluidlogged-API#30]
Swimming inside of fluidlogged blocks does not drag you down when wearing armour, unlike when swimming in the fluids themselves.

https://www.curseforge.com/minecraft/mc-mods/sink-or-swim

**Comment by jbredwards** [comment]
This is not an issue with my mod. Sink or Swim checks if the block below is replaceable (which fluidlogged blocks aren't), rather than checking if the block holds a fluid.
