### ISSUE TITLE
crash when right clicking loggable blocks with buckets filled with non placable fluids

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#33]
pretty much the title, if you try place a non placable fluid on a fluidloggable block, it causes this crash: https://pastebin.com/raw/NNkTrWUS

seems very consistent with all mods, try placing things like grassoline, tree oil or liquid xp from thermal foundation on a fluidloggable block.

**Comment by jbredwards** [comment]
fixed in v1.6.2!

**Comment by xemnes** [comment]
thank you!
