### ISSUE TITLE
crash with railcraft

### ISSUE THREAD

**Issue by yggdrasil75** [jbredwards/Fluidlogged-API#35]
**Describe the bug**
incompatibility with railcraft (presumably incompatibility actually resides with mcmultipart)

**To Reproduce**
install railcraft, mcmultipart, fluidlogged api and a bunch of others.
run game
crash.

**Expected behavior**
play game.

**Logs**
[crash report](https://gist.github.com/yggdrasil75/e2b885e48bcb2cd0fa869195ba93efbe/).

**Comment by jbredwards** [comment]
someone else had that same problem, [this](https://github.com/jbredwards/Fluidlogged-API/issues/23) was my solution. Let me know if it works for you was well.

**Comment by yggdrasil75** [comment]
that works. guess this just needs to possibly put checking fluids a little later somehow in the future?
