### ISSUE TITLE
Content Tweaker Liquid fluidlogged blocks get deleted by other liquids

### ISSUE THREAD

**Issue by Foreck1** [jbredwards/Fluidlogged-API#4]
I'm posting this issue because it relates to a liquid rather than a singular non-supported block.

Fluidlogged blocks (of any kind) containing any liquid created with Content Tweaker get completely deleted upon contact with any other flowing liquid that touches the blocks.

Pictured is a before and after, more cases were tested to corroborate this happens for all combinations
![image](https://user-images.githubusercontent.com/47757429/119511858-d3913e80-bd40-11eb-8277-c73ac9a5f798.png)
![image](https://user-images.githubusercontent.com/47757429/119511734-b3fa1600-bd40-11eb-9189-3c92097062d3.png)

**Comment by jbredwards** [comment]
fixed in release v1.4, sorry for the wait!
