### ISSUE TITLE
Quark Compat for Walls

### ISSUE THREAD

**Issue by Jerome226** [jbredwards/Fluidlogged-API#43]
**Is your feature request related to a problem? Please describe.**
I was building on my server, I realised all quarks walls didn't got fluidlogged like the other type of walls.

**Describe the solution you'd like**
It would be nice if Quark support would be added, so I could use stone bricks wall and other quark stuff in waterlogs.

**Describe alternatives you've considered**
Tried to use FutureMC walls, but quark walls have more variants and it would be better if it was compatible.

**Additional context**
![image](https://user-images.githubusercontent.com/55724525/149645982-d1094ae3-5cc0-49be-9dc8-b3e44fd4fcad.png)

**Comment by jbredwards** [comment]
this mod is currently being rewritten so the next release will have a config, I'll update the curse page to make this more known

**Comment by Jerome226** [comment]
Oh nice, will the new version be compatible with the old one since it's rewrited?

**Comment by jbredwards** [comment]
You should expect old worlds to not be compatible. I _might_ create an additional file when I'm finished that lets the old worlds work.

**Comment by Jerome226** [comment]
Oh shit okay, i have a map that use waterlogged stairs from this mod, so yeah im gonna need to convert all of these.

**Comment by jbredwards** [comment]
> You should expect old worlds to not be compatible. I _might_ create an additional file when I'm finished that lets the old worlds work.

Update: this is no longer true lol, there will be backward compatibly built-into the new version, so old worlds will be fine!

**Comment by Jerome226** [comment]
Nice! Looking forwards for a full release of the rewrite.

**Comment by jbredwards** [comment]
1.7 is out on curse!
