### ISSUE TITLE
Fluidlogged-API-v1.7-mc1.12.2.jar Redstonetorch and Redstonewire problem

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#49]
Hi,
I have a Problem with your Mod by 2 thinks what can Waterlogged 

Problem:
In the end of this Bug Report have I 2 Pictures. The Problem is the Redstonetorch and the Redstonewire was not Waterlogged then we Place this on the World. The other Blocks works fine but the Redstonetorch and the Redstonewire was not Waterlogged. I have with Mods Play and have all Mods deleted and the same think was come. A Bug what only in your Mod is. You can check this Mods out and I hope you can find a fix for this. The new thinks was cool but then the Waterlogged Function not correct work by the Redstonetorch and the Redstonewire and he drop then we will Waterlogged then is it not good. I hope you find a Fix for this.

Forge Version:
I play with Forge 1.12.2 - 14.23.5.2860

Recreate this Bug:
1. Go to your World and Build a Watertank or go to the Sea.
2.  Place a Redstonetorch and Redstonewire
3.  You see the Block who you have this Place is Free from Water and not Waterlogged
4.  Replace the air of this Block who this Items place was with a Waterbucked and the Item drops and hold not of the Ground

All Mods in this Moment:
- Fluidlogged-API-v1.7-mc1.12.2 (Your Mod)
- [1.12.2]+SecurityCraft+v1.9.1 (Safer Mod for Minecraft with new Gagdets)
- frikinzis-fauna-1.3.0-1.12.2 (New Animals for Minecaft)
- Orva+Alarms+2.3+1.12.2 (Sound Mod)
- parkour_recorder-1.1.2.0-1.12.2 (Only Record of a szene)
- movingelevators-1.3.4-mc1.12 (Mod with Elevator Build and Play)
- supermartijn642configlib-1.0.9a-mc1.12 (Require for movingelevator)
- durabilitytooltip-1.1.0-mc1.12 (tooltip mod)
- Expansive+Weaponry-1.1.0 (Weapons Mod)
- FishingMadeBetter-1.12.2-2.2.2 (A new Minigame by Fishing in Minecraft)
- ElytraBombing-Forge-1.12.2-1.0.0 (A Mod with new Function for the Elytra)
- CDM-v1.12.2-1.1.00 (City and Car Decorations with Decocars)
- Fexcraft+Common+Library-1.12.71 (Require Mod for CDM = Cities Deco Mod (Formally Saracalia's City Mod))
- geckolib-forge-1.12.2-3.0.21 (Require mod for the Animals Mod frekinzis fauna)
- supermartijn642corelib-1.0.16a-mc1.12 (Require for movingelevator)
- FancyClear-Forge-1.12.2-1.3.1.1 (Clear Mod for Mobs then to much was on a World (This Version give it not on Curse but on all my 1.12.2 Modpack can you claim this (Link: https://drive.google.com/file/d/1ZnYAm-E720m53lzr1EAEY_WhYpsjEbo5/view)
- MixinBootstrap-1.1.0 (Require Mod for your new Mod Update)

Pictures of the Problem:
![2022-03-18_17 51 42](https://user-images.githubusercontent.com/42325138/159047810-776354e6-7b30-41d2-8fa1-09a8a352414f.png)
![2022-03-18_17 51 55](https://user-images.githubusercontent.com/42325138/159047827-abd20b43-5f2b-4f2d-804f-2761aff8a28c.png)

**Comment by jbredwards** [comment]
whoops, I forgot to actually go ahead and implement those lol, a fix will be out in a few min

**Comment by Titoo8899** [comment]
hi,
a okay thanks for your fast answer your mod find I with this mod very good and I was happy then the last thinks work. :D

**Comment by Titoo8899** [comment]
I will test the new Version

**Comment by Titoo8899** [comment]
But I hope you can a Video make for the Blacklist and the Whitelist how we can add Blocks

**Comment by Titoo8899** [comment]
Okay I have testet and it works fine. Thanks
