### ISSUE TITLE
Crash with FutureMC

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#5]
Something in the last updates broke compatibility with FutureMC, here is the [log](https://pastebin.com/iAT6SrX8)

**Comment by jbredwards** [comment]
that was an easy fix. Strangely the Future MC mod's asm class transformer doesn't seem to account for other mods. Made mine load after, as it actually accounts for other mods, and worked fine. What caused the sudden crash was the fix in 1.3 that allows players to see block selection boxes underwater. Apparently Future MC does that too lol

**Comment by jbredwards** [comment]
Just a heads up, don't put optifine in your server's mod folder, as it's a client only mod. I don't think optifine does anything if loaded by the server, but still not a good idea.

**Comment by Druwan-ctrl** [comment]
This time i sent you the log from the client, you can see sponge is missing! Thank you for the fast fixes! Will test it more while playing on the server later
