### ISSUE TITLE
[Feature] Better Water Rendering?

### ISSUE THREAD

**Issue by whatsapp2** [jbredwards/Fluidlogged-API#51]
I've been testing the fluid logging features for a bit and I've stumbled into a somewhat frustrating water rendering issue.
![2022-03-18_16 27 00](https://user-images.githubusercontent.com/25994176/159092854-d83ba519-39f9-4cfb-965a-7632a97789d0.png)
Water blocks are like separated and create this weird effect when water logging the multiblock

I would like to suggest a fixing for this issue if possible. As far as I know this might be caused by hbm mod itself and not fluidlogged mod

**Comment by jbredwards** [comment]
Fluids will always render on sides they can't flow from (usually non-solid sides). This is an issue with the mod's blocks not having correct `getBlockFaceShape` values.
