### ISSUE TITLE
Incompatibility with Twilight Forest

### ISSUE THREAD

**Issue by GruudeMann** [jbredwards/Fluidlogged-API#55]
Attempting to make a twilight forest portal will result in the diamond failing to trigger the portal activation, and will just sit at the bottom of the pool. Uninstalling this mod allows it to trigger just fine, so I know I'm not doing anything wrong here.

![2022-03-19_01 05 38](https://user-images.githubusercontent.com/101922173/159113251-74bd7ccf-d793-4b02-9ca2-732cfbc9db68.png)

[latest.log](https://github.com/jbredwards/Fluidlogged-API/files/8308824/latest.log)

Only with these two installed, so I know no other mods are interfering

**Comment by Rongmario** [comment]
TF checks [if the `IBlockState` the item entity is == `Blocks.WATER.getDefaultState()` before creating the portal.](https://github.com/TeamTwilight/twilightforest/blob/87574e3df3b5e0ccf9e0b0d414e8a231a6bdb0e4/src/main/java/twilightforest/block/BlockTFPortal.java#L148)

Here is where it [fires.](https://github.com/TeamTwilight/twilightforest/blob/87574e3df3b5e0ccf9e0b0d414e8a231a6bdb0e4/src/main/java/twilightforest/TFTickHandler.java#L115)

**Comment by jbredwards** [comment]
fixed in v1.7.1
