### ISSUE TITLE
[bug] [duplicate] Aquaacrobatics bubble columns

### ISSUE THREAD

**Issue by Carvercarver1** [jbredwards/Fluidlogged-API#56]
Duplicating this here for easier tracking. [[BUG] Bubble colums not functioning after new FluidLogged API update ](https://github.com/Fuzss/aquaacrobatics/issues/79)

**Comment by embeddedt** [comment]
@jbredwards I assume it's because my bubble column class currently extends `BlockStaticLiquid`?

**Comment by embeddedt** [comment]
Never mind, it was an issue on my end caused by updating my mappings and not having an `@Override` annotation on a method which changed names. This can be closed.

**Comment by jbredwards** [comment]
@embeddedt oh thank god you figured this out lol, my brain was drawing a blank
