### ISSUE TITLE
[BUG] weird thebetweenlands behavior.

### ISSUE THREAD

**Issue by Carvercarver1** [jbredwards/Fluidlogged-API#60]
Trying to place a fluidloggable object into swamp water will get that object deleted. To replicate it enter the dimension or pick swamp water and try to place anything, like a fence or anything else. It will get deleted from the water.

**Comment by Carvercarver1** [comment]
Addendum: anything OTHER than thebetweenlands things. So their underwater stalagmites and such, as well as some things meant for underwater, will not get deleted. However ordinary stairs will. And it happens only with swamp water, as tar and etc will not remove the item.

**Comment by jbredwards** [comment]
fixed in v1.7.1
