### ISSUE TITLE
[BUG] Strange Render

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#62]
**Describe the bug**
Some blocks from other mods looks odd when fluidlogged. In the screenshots I have blocks from [OpenComputers](https://www.curseforge.com/minecraft/mc-mods/opencomputers) and [Bibliocraft](https://www.curseforge.com/minecraft/mc-mods/bibliocraft). I can see why Bibliocraft might look a bit odd as it's a TESR, but I don't understand why OpenComputers does as it uses a regular model file for this particular block ([keyboard.json](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/resources/assets/opencomputers/models/block/keyboard.json)). But then again other mods will have a TESR that looks fine while fluidlogged.

**Screenshots**
![2022-03-20_12 15 28](https://user-images.githubusercontent.com/9884180/159670092-1ed0695f-dae0-4db7-97d9-8ef72737dee0.png)
![2022-03-20_12 13 18](https://user-images.githubusercontent.com/9884180/159670151-8e13218c-521d-4a35-ac10-2328eb29dd8d.png)

**Comment by jbredwards** [comment]
This is caused by the those blocks not implementing `Block.getBlockFaceShape()` correctly (see #51). I'm leaving is issue as open for now, so no one else creates issues related to this one.

**Comment by Rongmario** [comment]
For some reason modders prefer to use `isSideSolid` (apart from Bibliocraft which doesn't even do anything to signify the block's sides' solidity). Perhaps an extra check? It's quite a hotspot so it would need testing.

**Comment by jbredwards** [comment]
I'm messing with the idea of adding an optional `canFluidFlow` bool tag to the config whitelist & blacklist args, which'll offer a workaround until the mods can fix the issues themselves.

**Comment by embeddedt** [comment]
> which'll offer a workaround until the mods can fix the issues themselves.

Unfortunately, I doubt this will happen. Very few mods are still maintained for 1.12, or would even make another release even if a fix were contributed by the community.

**Comment by jbredwards** [comment]
optional whitelist arg "canFluidFlow" bool added in v1.7.2
