### ISSUE TITLE
Provide obfuscated builds on Jitpack as well

### ISSUE THREAD

**Issue by embeddedt** [jbredwards/Fluidlogged-API#63]
**Is your feature request related to a problem? Please describe.**

Many mods use `stable_39` mappings and cannot include a `snapshot_20171003` dependency directly. The usual workaround for this is to depend on the obfuscated build and use `deobfCompile` (or `compile fg.deobf`) to deobfuscate to the project's own mappings. However, this doesn't seem to be available on JitPack.

**Describe the solution you'd like**

Add a deobf artifact to JitPack.

**Describe alternatives you've considered**

Depending on the build on CurseForge using CurseMaven, which is my current workaround. However, that doesn't work if I want to depend on an unreleased version.

**Comment by jbredwards** [comment]
I reimplemented the source & deobf artifacts from v1.6.2, but it seems like the stable_39 mappings don't wanna work outside the dev environment :confused:

**Comment by embeddedt** [comment]
Is JitPack still broken? I can't seem to get an actual JAR out of it. https://jitpack.io/com/github/jbredwards/Fluidlogged-API/9ff5d0c/build.log only seems to list the sources JAR and nothing is downloaded when I check my Gradle cache.

**Comment by jbredwards** [comment]
As someone who isn't good with gradle, this is confusing. Jitpack.io was working at some point (probably pre v1.6.2), but I can't get it working now either. The only difference I notice is that this build.gradle uses mixin, does that perhaps have something to do with this?

**Comment by embeddedt** [comment]
@jbredwards I think #65 will fix it, just waiting for JitPack to build the PR to make sure.

**Comment by embeddedt** [comment]
I can confirm that that build worked fine.

**Comment by jbredwards** [comment]
awesome ty! <3
