### ISSUE TITLE
[BUG] "validFluidNames" in configs is ignored

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#69]
**Describe the bug**
Entries in the configs ignore what fluids a block can be fluidlogged with.
```json
"whitelist":[
	{"blockId": "botania:avatar","validFluidNames":["water"]}
]
```

Specifying "lava" in the blacklist does not make any difference either.
```json
"blacklist":[
	{"blockId": "botania:avatar","validFluidNames":["lava"]}
]
```

**Expected behavior**
Only water should be able to be fluidlogged in `botania:avatar` block.

**Comment by jbredwards** [comment]
The "validMeta" & "validFluidNames" were the dev names for the args, they were changed to "metadata" & "fluids" before releasing v1.7, I completely forgot sorry :worried:
