### ISSUE TITLE
weird crash, unable to replicate.

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#7]
hello, ran into this odd crash when just simply testing the waterlogging. placed it down in a fence, then turned around and looked at a villager and crashed 
https://paste.mod.gg/qujuxadoci.mccrash

edit: i think ive managed to replicate it, the crash happens with f3 debug open and i look at any water near an entity.

**Comment by jbredwards** [comment]
will be fixed next update!
