### ISSUE TITLE
New Waterlogged Blocks/Items etc. (Vines and Enchantment Table)

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#70]
I have 2 thinks what I hope you can add to your list of thinks from Minecraft what we can Waterlogged. 

The First was the Vines. The Vines can we only on the 1 waterblock place but the water Destroy this. I hope you can this to your list
add and Waterlogged for this make for make the world looks so better.

The Second think is the Enchantment Table. It is the last Block from Minecraft what not Waterlogged is and the Water on the Top of this not work and we a Air Area have. I hope you can this in the next Update add.

**Comment by jbredwards** [comment]
As of v1.7.2b, enchantment tables are now fluidloggable by default. I decided not to do this with vines cause it'd be inconsistent with the behavior of the other plants. You can always add vines to your config though!

**Comment by Titoo8899** [comment]
Hi,
okay this with the Vines okay then you will this not add. But I have a Waterwall Bug Found by the Enchantment Table found then I this place in the water on all sides was this waterwall and the area of the book on the top was with air. I hope you can fix it or a check function for this Problem. Look the Picture and you can see what I mean.

![2022-03-27_21 05 07](https://user-images.githubusercontent.com/42325138/160296727-46a57d89-2167-4a7b-a207-0d420b3b53c7.png)
