### ISSUE TITLE
[SUGGESTION] Define lists in config JSON

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#71]
**Is your feature request related to a problem? Please describe.**
It would be neat if you could define lists of liquids:

```json
"fluidTypes": [
	{
		"name": "water",
		"fluids": ["water","toughasnails:purified_water"]
	},
	{
		"name": "hot",
		"fluids": ["lava","somemod:liquid_iron"]
	}
],
"whitelist":[
	{"blockId": "botania:avatar","fluidType": "water"},
],
"blacklist":[
	{"blockId": "minecraft:chest","fluidType": "hot"},
	{"blockId": "minecraft:trapped_chest","fluidType": "hot"}
]
```

**Describe the solution you'd like**
Right now you have to change every entry in the list if you want to have a block be fluidlogged in a certain fluid.

**Comment by jbredwards** [comment]
added in v1.7.2b with this format:

```json
"fluidTags": [
	{
		"id": "water",
		"fluids": ["water","toughasnails:purified_water"]
	},
	{
		"id": "hot",
		"fluids": ["lava","somemod:liquid_iron"]
	}
],
"whitelist":[
	{"blockId": "botania:avatar","fluidTags":["water"]},
],
"blacklist":[
	{"blockId": "minecraft:chest","fluidTags":["hot"]},
	{"blockId": "minecraft:trapped_chest","fluidTags":["hot"]}
]
```
It's also possible to define fluids alongside fluidTags within the whitelist & blacklist. Note that you'll have to write the "fluidTags" arg yourself within the config, as it's optional.
