### ISSUE TITLE
Waterwall of the Enchantment Table by Test of this Waterlogged function

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#72]
Hi,
okay this with the Vines okay then you will this not add. But I have a Waterwall Bug Found by the Enchantment Table found then I this place in the water on all sides was this waterwall and the area of the book on the top was with air. I hope you can fix it or a check function for this Problem. Look the Picture and you can see what I mean.
I have tries with a Bucket of Water to clear this but the Wall can I with this not deleted.

![2022-03-27_21 05 07](https://user-images.githubusercontent.com/42325138/160296815-ae065e6c-7dcf-4594-8e99-8bd31182d888.png)

**Comment by jbredwards** [comment]
that shouldn't be happening, are you sure you downloaded v1.7.2b?

**Comment by Titoo8899** [comment]
ah okay I have the newest version not. I play with 1.7.2. I look the newest and then it works then close I this.
