### ISSUE TITLE
Crash while flying around, with MAGE and FoamFix

### ISSUE THREAD

**Issue by Luke616** [jbredwards/Fluidlogged-API#73]
**Describe the bug**
Random crash while flying around - seems to be an interaction with MAGE and FoamFix

**Logs**
[crash-2022-03-28_13.57.51-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/8365123/crash-2022-03-28_13.57.51-client.txt)

**Versions Used**
Fluidlogged API v 1.7.2b
Minecraft Forge v 14.23.5.2860
MAGE v 0.2.4
FoamFix 0.10.14

**Comment by embeddedt** [comment]
I don't think the smooth water fix implemented by MAGE is needed when Fluidlogged API is installed. Is there another mod you have that depends on it, or can you just remove it?

**Comment by Luke616** [comment]
Wasn't aware of that - removed it and flying around a new world now, thanks

**Comment by Luke616** [comment]
Potentially related - could this issue be a FluidLogged API bug? Haven't experienced it since before updating Fluidlogged from 1.6 -> 1.7.2b but the log is not at all descriptive. Also happens while flying around the world. Had this happen one before removing MAGE/smooth water and twice after removing them

[crash-2022-03-28_15.09.57-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/8365646/crash-2022-03-28_15.09.57-client.txt)

**Comment by jbredwards** [comment]
Can you send the full log (not just the crash report), the crash seems to be related to a mixin that some other mod is applying to the `Chunk` class. The log might tell me which mixin that would be

**Comment by Luke616** [comment]
Sure, here's the full log from that test session. Thanks for taking a look at it!
[2022-03-28-6.log](https://github.com/jbredwards/Fluidlogged-API/files/8366028/2022-03-28-6.log)

And here is my fluidlogged api config file
https://pastebin.com/XsRD5zRX

 Just flew around in a world for ~30 min without Fluidlogged API and did not see the crash, reinstalling now and trying to replicate the crash again currently

**Comment by Luke616** [comment]
Just confirmed fluidlogged API is the culprit, going to make a new issue

**Comment by jbredwards** [comment]
moved to #75, closing
