### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [jbredwards/Fluidlogged-API#77]
Is this mod compatible with optifine?

**Comment by jbredwards** [comment]
Yes (vG5 only), and any shaderpacks should work fine out of the box

**Comment by Fireworkstars46** [comment]
Cause I have optifine and for some reason the water is invisible when I log the blocks. The game doesn't crash but it's invisible and I can see it

**Comment by jbredwards** [comment]
Make sure you're using the G5 version, nothing earlier is compatible

**Comment by Fireworkstars46** [comment]
The optifine version I have is HD_U_G6_pre1 Ultra for 1.12.2

**Comment by jbredwards** [comment]
> The optifine version I have is HD_U_G6_pre1 Ultra for 1.12.2

Oh cool I didn't know there was a version higher for 1.12. For now I'm not going to update compat though, because doing so would ruin compat for the earlier versions, G6 is currently in beta, and according to the changelog only two things changed:
```
 - fixed MacOS crash when using newer JDK versions (#4824)
 - compatible with Forge #2847
```
I'm pretty sure the last change listed does nothing anyway, that's the version of forge I use already and G5 works fine with it lol

**Comment by Fireworkstars46** [comment]
So is my version the issue or?

**Comment by jbredwards** [comment]
Yes, downgrade to G5

**Comment by Fireworkstars46** [comment]
Ok I got that version and it's still the same

**Comment by jbredwards** [comment]
Can you send your mod list?

**Comment by Fireworkstars46** [comment]
https://pastebin.com/tjbp6YyP

**Comment by jbredwards** [comment]
Nothing's popping out at me, would you mind also sending your log? In the meantime remove MixinCompat, you don't need that as well as MixinBooter

**Comment by Rongmario** [comment]
SteveKunG's-Lib depends on MixinBooter

**Comment by jbredwards** [comment]
@Rongmario I meant keep MixinBooter & remove MixinCompat, so I guess it works out

**Comment by Fireworkstars46** [comment]
So remove that one file?

**Comment by Fireworkstars46** [comment]
I found out the issue. Turns out there's a optifine setting that had to be turned off. I'll share images of it.

**Comment by Fireworkstars46** [comment]
First 2 images is the bug and setting on 
![2022-04-20_07 33 21](https://user-images.githubusercontent.com/30112538/164222097-c23f2f72-6aa2-4b02-92c9-6be19f5e08de.png)
![2022-04-20_07 33 32](https://user-images.githubusercontent.com/30112538/164222098-b16eaca8-a5e0-4d12-b67d-7786bcc329a3.png)
![2022-04-20_07 33 47](https://user-images.githubusercontent.com/30112538/164222099-44fa706a-808e-4468-8aa7-b9af1274f490.png)
![2022-04-20_07 33 58](https://user-images.githubusercontent.com/30112538/164222100-54189ccf-59e1-4a40-9ebb-e4e85549d259.png)
and the next 2 images is the bug fixed and setting off
