### ISSUE TITLE
waterlogged blocks water level doesnt match height of water surrounding it

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#8]
heres a video of whats going on 
https://gfycat.com/WastefulFancyBarasinga

the only thing i can think of that could cause this is the smooth water mod.

**Comment by jbredwards** [comment]
the height is fine without the mod installed. I took a look at the mod's source code, and found that I actually can't do anything about your issue. There are two problems in my way.

1. The mod adds a unique system for rendering the vanilla fluid blocks.
2. The mod blacklists itself from asm transformations, which means I can't change their new system on my end for mod compatibility.

Sorry if this is disappointing, but I think the fix has to be done from their side. If this changes, I'll make sure to add compatibility! I think the fix coming from their side also makes more sense in general, as they wouldn't need to apply any asm.

**Comment by xemnes** [comment]
thats a shame, in that case, my only option would be to remove the mod as the dev is no longer updating it. the source code is available however though sadly i have dont have enough knowledge to do it myself. would it be possible to implement smooth water into this mod instead?

**Comment by jbredwards** [comment]
just created a pull request for the mod [here](https://github.com/asiekierka/MageMC/pull/15). If they accept, the issue should be fixed

**Comment by xemnes** [comment]
oh nice, thank you!
im capable of building it myself so i dont think i will be waiting around for them to accept your pr lol.
one thing i will probably have to do is move the fix to the standalone smooth water mod rather than mage. since i run optifine, mage might clash with it, i think i can manage it.

**Comment by xemnes** [comment]
hmm went ahead and tried out your pr, i found that i couldnt build it due to this gradle error

> Build file 'E:\.minecraft\realmofstorms\source files\MageMC\build.gradle' line: 130
> 
> A problem occurred evaluating root project 'MageMC'.
> > Could not get unknown property 'keyStore' for root project 'MageMC' of type org.gradle.api.Project.

so i removed the shadowjar block just to see if it built without it and it did.

went ahead and loaded the game up with the custom build of mage and your mod, and sadly i crashed before the game window even opened :(

there was no crash report, but i have the latest log
https://pastebin.com/ZGizfftN

im not sure what it means, not sure if its because of the modified code or not.

edit: its not, the non modified version of mage also crashes, this isnt an issue with the standalone smooth water mod.
made sure all the features except smooth water is off in the mage config too, hmmmm.

ive yet to try and see if your changes are compatible with the standalone mod. will edit if i have more info on that.

edit2: so actually, it turns out, its fluidlogged that is causing the crash, v1.4.2.

**Comment by jbredwards** [comment]
moved to a new issue, since I don't think this relates to the original
