### ISSUE TITLE
Incompat.  with Better Builders Wands.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Fluidlogged-API#80]
**Describe the bug**
Better Builders Wands with this mod do not function at all.

**To Reproduce**
Install this mod with Better Builders Wands and try using its wands like usual.

**Expected behavior**
Better Builders Wands working like normal.

**Screenshots**
Normally you'd see white hitboxes showing what the wand is gonna make. Using the wand does nothing.
![2022-04-14_07 00 59](https://user-images.githubusercontent.com/51277766/163407021-e23aae29-719e-4f82-ae97-9f098f0ca546.png)

**Logs**
No logs related to this occur.

**Additional context**
N/A

**Comment by jbredwards** [comment]
That's very strange, I'll see if I can fix it. Sorry for the late reply, taking a short break from this mod due to being burned out

**Comment by MagmaSlime123** [comment]
You're good. Though this and the Phosphor issues are kinda preventing me from using this.

**Comment by jbredwards** [comment]
After some testing, the issue lies with Better Builder's Wands. It uses a bad `targetBlock.isReplaceable` check [here](https://github.com/portablejim/BetterBuildersWands/blob/59975138a352aa69ab4c06db04c9bbf456a4f5b0/src/main/java/portablejim/bbw/core/WandWorker.java#L129), I'll asm patch it the meantime, since I doubt the mod will update anytime soon (no curse releases and no recent git activity)

**Comment by MagmaSlime123** [comment]
Ah, alright. Sorry for not mentioning.

**Comment by jbredwards** [comment]
what are you apologizing for? you're all good :)

**Comment by MagmaSlime123** [comment]
Been a while, has this been fixed yet?

**Comment by jbredwards** [comment]
yes, just not released to curse yet, working on removing mixins first

**Comment by jbredwards** [comment]
fixed in v1.8.0

**Comment by MagmaSlime123** [comment]
@jbredwards Apparently 1.8.0 now causes a render crash with the mod

https://pastebin.com/5bEKzX7U

**Comment by jbredwards** [comment]
welp, apparently builder's wands doesn't like `ClassWriter.COMPUTE_FRAMES`, fixed in v1.8.1b

**Comment by MagmaSlime123** [comment]
Thanks!
