### ISSUE TITLE
Crash on launch with futuremc

### ISSUE THREAD

**Issue by IO2I** [jbredwards/Fluidlogged-API#84]
**Describe the bug**
Game Crashes on launch when using futuremc

**To Reproduce**
1. Launch game with futuremc
2. Crash

**Expected behavior**
Game launches as normal

**Logs**
https://gist.github.com/IO2I/da4b83ecd884dd92e58067a200eec75f

**Comment by embeddedt** [comment]
It appears that you are using an old version of Future MC (0.2.6) in spite of the filename having 0.2.8 in it. That is the reason for your crash.

**Comment by IO2I** [comment]
Ok. Upgrading to futuremc 0.2.9 fixed the issue. Thanks for your help and sorry for any inconvenience.
