### ISSUE TITLE
Serverside Incompatibility with Buildcraft Energy 

### ISSUE THREAD

**Issue by gnomed-by-steve** [jbredwards/Fluidlogged-API#85]
This is a crash on launch due to a conflict with fluidlogged and buildcraft causing BC to make calls to EntityPlayerSP on load.

install Fluidlogged API 1.8.0 (commit 60c5dbc6a74c3cf9ea0d66fc91d77f82864cecae} and Buildcraft-all 7.99.24.8 to a minecraft forge server
in the terminal, it should show a crashlog.

Lastest: https://pastebin.com/UF9Fn7ie
Crash Report: https://pastebin.com/3568Hk8L

Issue persists with latest commit as well.

**Comment by jbredwards** [comment]
After some further testing, this is not a problem with buildcraft, the crash happened when my `ASMHooks` class was loaded. Throwing a `SideOnly` annotation at `fixBarrierParticles` fixed the crash for me lol, try the latest commit & see if it works for you as well

**Comment by gnomed-by-steve** [comment]
Yup, just put it in my server and got no further issues, thanks a bunch!

**Comment by gnomed-by-steve** [comment]
misinput, forgot that this is only fixed in the latest commit and not a release

**Comment by jbredwards** [comment]
closing this, since I don't think this issue affects v1.7.2b
