### ISSUE TITLE
Looking at a mob with F3 activated crashes the game

### ISSUE THREAD

**Issue by oneoffourSE** [jbredwards/Fluidlogged-API#9]
1. Spawn any mob.
2. Press F3.
3. Look at the mob.
4. See the game crash.
I tried it with only this mod activated.

[crash-2021-05-29_20.20.19-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/6566305/crash-2021-05-29_20.20.19-client.txt)

**Comment by jbredwards** [comment]
https://github.com/jbredwards/Fluidlogged-API/issues/7
