### ISSUE TITLE
Betweenlands Swamp Reeds cannot generate, and pop off as items.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Fluidlogged-API#90]
**Describe the bug**
If this mod is used, see title.

**To Reproduce**
Install both mods, enter the Betweenlands dimension, go to a Swamplands biome, and fly around. Should see Swamp Reed items everywhere.

**Expected behavior**
Swamp Reeds to generate normally.

**Screenshots**
![2022-05-12_11 28 17](https://user-images.githubusercontent.com/51277766/168134334-c07acfdf-bcd3-4ed1-9ff2-157b2cf784d3.png)

Without the mod:
![2022-05-12_11 37 31](https://user-images.githubusercontent.com/51277766/168135530-d43c12ef-3ca7-46c2-a4d8-3c266bed6350.png)

**Logs**
N/A

**Additional context**
There's probably other blocks that don't generate correctly, but so far, Swamp Reeds are the most noticeable.

**Comment by jbredwards** [comment]
fixed in v1.8.1
