### ISSUE TITLE
Likely a new sponge compability crash

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#92]
Not really sure if it's because of sponge but it sure gets nominated often

**Logs**
[This ](https://gist.github.com/Druwan-ctrl/5050c6ce990f35fe1fc8c7cdb80569e0)is the debug part related to the crash

I think it's related to this:
-fixed block.onEntityCollision with FluidStates, now only occurs if the entity is within the fluid

**Comment by jbredwards** [comment]
By the looks of things, a mixin transformer wants a method to be present that one of this mod's transformers moves to [here](https://github.com/CleanroomMC/Fluidlogged-API/blob/d9d74570396af831d2a556ebedcbc07631f39405/src/main/java/git/jbredwards/fluidlogged_api/mod/asm/plugins/ASMHooks.java#L1240). I'll rework the transformer so the method is still directly present after all is done.

**Comment by jbredwards** [comment]
fixed in v1.8.1
