### ISSUE TITLE
crash with sledgehammer

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#95]
getting this crash with sledgehammer on v1.8.0

https://pastebin.com/R1D7TyN9

it is however fixed by setting optimize-liquid-drain to false in sledgehammers config. unsure if its needed or not but its a workaround for now at least.

**Comment by embeddedt** [comment]
@jbredwards can probably comment on whether or not Fluidlogged API has done or can make the same optimization internally, but the Sledgehammer option will definitely need to be disabled, as Fluidlogged overwrites that method.

**Comment by xemnes** [comment]
i felt like it did before but the conflict was fixed. unsure though. it wasnt happening until now at least.

**Comment by jbredwards** [comment]
fixed in v1.8.1

**Comment by xemnes** [comment]
thank you!
