### ISSUE TITLE
Water Rendering Issue

### ISSUE THREAD

**Issue by SaltSouls** [jbredwards/Fluidlogged-API#97]
**Describe the bug**
When a waterloggable block is placed in one of the corners of a pool of water, the water fails to render.

**To Reproduce**
1. create a pool of water.
2. try placing a waterloggable block in any of the corners.
3. watch water disappear.

**Expected behavior**
Water should not become invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/36361103/169672865-7070ae9b-25b9-4e3f-9a25-3a6e0714f52f.png)
![image](https://user-images.githubusercontent.com/36361103/169672872-7d01f438-eb7c-49c3-8bbc-86f5d958b1d9.png)

**Logs**
https://gist.github.com/SaltSouls/bee33e532aadeb9290b0bbcf29f17e92

**Additional context**
It seems to be some kind of compatibility issue with Optifine as removing it fixes the issue.

**Comment by embeddedt** [comment]
Are you using shaders, and what are your options set to under Performance (Fast Render, etc.)?

**Comment by SaltSouls** [comment]
Smooth FPS: on
Fast Render: off
Chunk Updates: 1
Render Regions: on  <-- This seems to be the issue as turning it off fixes it.
Smart Animations: on
Smooth World: on
Fast Math: on
Dynamic Updates: on
Lazy Chunk Loading: on

**Comment by SaltSouls** [comment]
I do have internal shaders on, but the issue persists even when shaders are turned off.

**Comment by embeddedt** [comment]
FYI: fast render, render regions and lazy chunk loading are considered problematic with mods. It might be possible to fix this but I wouldn't recommend playing with those options enabled in a modpack.

**Comment by SaltSouls** [comment]
That is good to know. I wasn't aware that those in particular caused issues.

**Comment by SaltSouls** [comment]
On a side note, standing near water when on a farmland block will treat the player as if they were standing in the water.

**Comment by jbredwards** [comment]
> On a side note, standing near water when on a farmland block will treat the player as if they were standing in the water.

ok that's kinda funky lol, that'll be fixed next update

**Comment by jbredwards** [comment]
fixed in v1.9.0.0 (probably)
