### ISSUE TITLE
Compatibility with coral reef mod

### ISSUE THREAD

**Issue by wormzjl** [jbredwards/Fluidlogged-API#98]
**Describe the bug**
https://www.curseforge.com/minecraft/mc-mods/coralreef
Coral reef looks fine without fluidlogged api installed, but stuff looks broken and adding to whitelist doesn't work
![image](https://user-images.githubusercontent.com/2989009/169676043-a7743005-ec0c-4219-8381-9f89d0b37036.png)

**Comment by jbredwards** [comment]
This is a problem on coralreef's end. I fixed this from my side since the mod is archived & won't receive updates

**Comment by jbredwards** [comment]
fixed in v1.8.1
