### ISSUE TITLE
Fluidlogging does not work without block update on lost cities generated blocks

### ISSUE THREAD

**Issue by wormzjl** [jbredwards/Fluidlogged-API#99]
**Describe the bug**
I've been using lost cities mod to generate underwater ruins, but it appears that fluid logging won't work unless there is a block update around the concerned blocks.
It looks like this:
![image](https://user-images.githubusercontent.com/2989009/169676138-ee397b19-9c9a-4a51-8147-0f35bd8e3543.png)

**Comment by jbredwards** [comment]
This must be fixed from their side. The next update of Fluidlogged API (v1.8.2) will allow `ChunkPrimers` to handle `FluidStates`, which will make a fix very easy to add if the lost cities devs decide to implement one.
